### ISSUE TITLE
PDP11:ts magtape device does not work under (at least) RSX11M-PLUS

### ISSUE THREAD

**Issue by alawrence011** [simh/simh#523] opened 2018-02-04 17:44 UTC
I'm a newbie here and not a code writer so difficult to comment sensibly, however under RSX11M-Plus the magtape in ts fails to read correctly. Attempts to read from it produce a variety of system error messages which imply that the data being retrieved (using eg $FLX) is incorrect. There are no problems using the ts device in release 3.90.
Sorry - best I can do - can't read C of any variant.

**Comment by markpizz** [comment] 2018-02-04 22:22
There is no need for you to understand or even look at the code.  However, if something didn't work as you expected, then you certainly know how it failed and how you expected it to work.  The template to create this issue report asked for those details, so that someone else can easily reproduce the problem and once the problem is reliably reproducible, a fix can be worked on.

- #### Please provide the following details:
- #### Please Provide a general summary of the issue in the Title above
- #### Context

You seem to have done this.

- #### Provide a more detailed introduction to the issue itself, and why you consider it to be a bug or why the suggested change or enhancement would be useful

Maybe not necessary given the detail provided.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

MISSING.

- #### how you built the simulator or that you're using prebuilt binaries

MISSING

- #### This should include the output produced by while building just the simulator that is exhibiting the problem 

MISSING

- #### the simulator configuration file (or commands) which were used when the problem occurred.

MISSING
- #### The simulator configuration file, and any other relatively small files can be attached to this issue now or after it is created
MISSING
- #### the expected behavior and the actual behavior
MISSING
- #### Please provide the output the simulator produced when you experienced the problem
MISSING

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

MISSING

- ####  If you haven't already, please be sure that your full name is visible in your Github profile (no email address is needed)

MISSING


I'm closing this issue for now.  When you provide enough detail to reproduce the problem, feel free to re-open it and we can look for a fix.

Thanks.

**Closed by markpizz** 2018-02-04 22:22 UTC

**Comment by alawrence011** [comment] 2018-02-05 18:35
Far too much work to provide all this detail. I'd have been happy to do a
bit but I'm not going to spend a couple of hours to work all the way
through a system build just to get to the error messages.

Since 3.9 works fine I'm happy to dump the 4.0 beta.
Sorry.

**Comment by markpizz** [comment] 2018-02-05 19:07
Without reproducible detail, your report is a rumor.  :-)  Sorry.
