### ISSUE TITLE
vax780 tq doc discrepancy

### ISSUE THREAD

**Issue by hbent** [simh/simh#265] opened 2016-01-12 15:50 UTC
In the vax780 simulator, "HELP CPU" implies that it can be booted from a TQ device:

"TQn        to boot from tqn"

but attaching a tape to tq0 and trying to boot doesn't work:

sim> sh tq
TQ      TU81 (180MB), address=2013F940-2013F943, no vector, 4 units
  TQ0   attached to blah.tap, write locked, SIMH format
        capacity=188MB
sim> boot tq
Command not allowed
sim> boot tq0
Command not allowed

This is with the latest sources from git.

**Comment by markpizz** [comment] 2016-01-12 16:32
The VAX780 boots by setting up parameters and passing control to VMB.EXE.

The TMSCP boot device code "#define BOOT_TK         18" had existed in vax780_defs.h way back in simh v3.5-1 when the VAX780 simulator was first added, as such the boot parameters to boot from the TQ device were known and VMB would be passed the appropriate parameters to boot from  this device.  The problem is that no one actually tested a a TMSCP boot on the VAX780 simulator until I did in December 2014 and noticed the fact that there was no code which used the parameters which were being passed.  As such, the logic to pass these parameters was removed from the VAX780 as well as the other simulators which also boot using VMB.  The information in the VAX780 help was missed when the boot logic was changed.  

Thanks for reporting this.

It is now fixed.

**Closed by markpizz** 2016-01-12 16:32 UTC
