### ISSUE TITLE
PDP8: FOCAL-69 doesn't print initialization message

### ISSUE THREAD

**Issue by drovak** [simh/simh#1017] opened 2021-03-03 00:43 UTC
I am using another PDP-8 simulator, which prints a message at the start of FOCAL-69:

```
loading focal69/dec-08-ajae-pb_7-9-69.bin...done
running...

CONGRATULATIONS!!
YOU HAVE SUCCESSFULLY LOADED 'FOCAL,1969' ON A PDP-8/I COMPUTER.


SHALL I RETAIN LOG, EXP, ATN ?:
```

Yet, when running the same tape with SimH, it jumps straight to the asterisk prompt:

```
sim> lo focal69/dec-08-ajae-pb_7-9-69.bin
sim> g 200
*
```
Am I doing something silly?

I'm using the paper tape from here: http://bitsavers.org/bits/DEC/pdp8/papertapeImages/set2/tray2/  

Version information:

```
PDP-8 simulator V4.0-0 Current        git commit id: 6c722311
sim> show version
PDP-8 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 7.5.0
        Simulator Compiled as C arch: x64 (Release Build) on Feb 22 2021 at 22:42:19
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        No RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux kyle-elitebook 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
        tar tool: tar (GNU tar) 1.29
        curl tool: curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
        git commit id: 6c722311
        git commit time: 2021-02-15T13:26:28-0800
```

**Comment by markpizz** [comment] 2021-03-03 13:06
If I were to guess, it would seem to me that you are not starting each of these cases at the same place...  It is obvious where you are starting the simh instance, but you will have to dig deeper into how the load and start activity of the other simulator actually happens.

**Comment by drovak** [comment] 2021-03-03 15:52
It is starting at 0200 in both cases. I've also tested it on the macOS PDP-8/E Simulator. It wasn't happy loading the paper tape, saying, "There is something wrong with the paper tape, maybe garbage before leader or after trailer." It appears as though it's the latter. Loading it with the BIN loader seems to work. I think there might be multiple segments on the tape. I might dig into it more to see what exactly is making the loading process unhappy, but it's interesting that SimH ate the tape, reporting no errors, yet the PDP-8/E Simulator refused to load it with its equivalent "load" command. Is there a way for SimH to tell the user when they appear to be loading a corrupt (or otherwise strange) paper tape?

**Comment by markpizz** [comment] 2021-03-03 19:33
Given your issues loading things, I would advise looking at the contents of memory after you succeed loading things on each simulator.  I suspect you may find different contents.

You may want to look at #74 since it may be relevant...

**Comment by drovak** [comment] 2021-03-03 23:37
Thanks, #74 indeed is relevant. Still would like to see maybe a little message printed that warns the user of a weird paper tape; seems like there are return values already set up for that, right?

**Comment by markpizz** [comment] 2021-03-04 22:42
Well, this comes down to exactly what is a weird paper tape.

When @dgesswein changed the loader module to add support for reading multiple sections from a tape, he kept the behavior of just reading one section of the paper tape as default since that was how things were always done in the past.  He added the -A switch and its related logic to read all sections of the tape.

I downloaded 21 files from  http://bitsavers.org/bits/DEC/pdp8/papertapeImages/set2/tray2/ and found ALL were one of bad format(1), checksum errors(4), or have extra, but not useful junk past the initial useful data.  Only 2 had more than one valid section of properly structured data.  So, from what I see, most paper tapes are at least a little weird.

Try using the attached pdp8_sys.c in [pdp8_sys.zip](https://github.com/simh/simh/files/6087015/pdp8_sys.zip) and see if this is reasonably behaved or too noisy.

**Comment by drovak** [comment] 2021-03-04 23:58
I think this is a great start! And very good points about what is a weird tape. I figured something assembled with `palbart` should not, in general, be considered a weird tape. But, it looks like even the most basic program assembled with `palbart` is tripping up the loader code, claiming `initial section loaded - bad format additional data ignored`. 

Do you think adding some logic to detect anything other than 0200 or 0 after the checksum of the BIN format would result in a message, but otherwise, valid trailer of 0200 or 0 would be considered fine?

**Comment by markpizz** [comment] 2021-03-05 00:30
It is just warning you that the rest of the tape doesn't contain useful structured data.  It hasn't failed to do what the command intended (i.e. load the first section).  In the event there are other well structured sections following the initial one it lets you know that they're there.  The detection process for these cases merely recursively invokes the same routine to read the rest of the file suppressing actions that effect memory.

> Do you think adding some logic to detect anything other than 0200 or 0 after the checksum of the BIN format would result in a message, but otherwise, valid trailer of 0200 or 0 would be considered fine?

The logic I sent doesn't change the interpretation of the data, it just elaborates via explanation what it conceptually has seen in the data.

Try this pdp8_sys.c [pdp8_sys.zip](https://github.com/simh/simh/files/6087380/pdp8_sys.zip), which as you suggested ignores extra 0's and 0200's after the first section.

**Comment by drovak** [comment] 2021-03-05 05:08
This seems to work great, Mark! Thank you very much. I can't think of any inadvertent side effects from this behavior, but perhaps @dgesswein or others can double-check this as well. 

Also, tangentially related, I noticed that if I try to `lo ~/Downloads/dec-08` and tab-complete, it successfully completes to `lo ~/Downloads/dec-08-ajae-pb_7-9-69.bin`, but I get a `File open error`. If I give it the full spec, it works fine. Is this intended behavior? I would've expected `~` to be expanded to `$HOME`, right?

Thank you again for your help!

**Comment by dgesswein** [comment] 2021-03-05 16:08
Long ago so don't really remember the reasoning. Probably leave things 
working the same for the default case.  There are tapes around with non 
zero or leader junk at the end which I thought might end up changing memory. 
Your method of checking for valid format without writing to memory solves 
the problem of the end junk doing wrong memory writes.

**Comment by markpizz** [comment] 2021-03-05 16:18
I just committed more or less the last example with two additional fixs.  
1) It seems that the handling of rubout characters in sim_bin_getc() was not being done according to how things are described in section 5 (page 4) of the DEC-08-LBAA-D manual.  I have fixed that and now more of the test tapes I was working with are valid.
2) For invalid tape sections (Format or Checksum), it displays the words that were modified before detecting the problem.

Please test and close this issue if things look good.

**Comment by markpizz** [comment] 2021-03-05 17:11
> Also, tangentially related, I noticed that if I try to lo ~/Downloads/dec-08 and tab-complete, it successfully completes to lo ~/Downloads/dec-08-ajae-pb_7-9-69.bin, but I get a File open error. If I give it the full spec, it works fine. Is this intended behavior? I would've expected ~ to be expanded to $HOME, right?

VERY TANGENTIALLY.... 

Well, I'm thinking that normally the ~/ expansion is done by the shell, but somehow readline seems to be doing that for you on your system after tab expansion.  I can't reproduce the behavior you claim to see on Linux or MacOS.  What platform are you using?

**Comment by drovak** [comment] 2021-03-05 22:32
I was unclear, sorry. The "$HOME expansion" I was referring to should probably say "substitution." This is on a standard Ubuntu install. I was not expecting readline to literally expand it as I tab-completed (though there are some shells that do that, I believe). My expected behavior was simply that if I can tab-complete a file, it should not have any trouble at least opening it, as I experienced.

Are you able to load files referenced with "~/"? 

Will check more on the tape behavior when I get another moment, but that behavior sounds quite good.

**Comment by markpizz** [comment] 2021-03-06 00:46
> I was unclear, sorry. The "$HOME expansion" I was referring to should probably say "substitution." This is on a standard Ubuntu install. I was not expecting readline to literally expand it as I tab-completed (though there are some shells that do that, I believe). My expected behavior was simply that if I can tab-complete a file, it should not have any trouble at least opening it, as I experienced.

It seems like you are saying that you can tab-complete a filename that starts with ~/ and then successfully load from the indicated file merely by hitting return.  This doesn't work for me on Ubuntu.

> Are you able to load files referenced with "~/"?

No.  Not yet - maybe soon once I understand what does and does not work for you.

**Comment by markpizz** [comment] 2021-03-07 20:13
Please try the latest code in the master branch to see if your original problem is addressed as well as references to ~/.

**Closed** 2021-03-13 14:54 UTC
