### ISSUE TITLE
pthread

### ISSUE THREAD

**Issue by TentacleMan** [simh/simh#284] opened 2016-03-07 18:06 UTC
Not sure if this is a thing with Arch Linux only but in order to compile the PDP11 simulator I had to edit slirp_glue/sim_slirp.c and add `#include <pthread.h>` (libslirp.h is included twice in that file btw) and instruct make to link with libpthread via an LDFLAG on the command-line.

**Comment by markpizz** [comment] 2016-03-07 18:13
Please provide some more specifics on exactly what your environment is (what OS/distro/version, etc.)

Also provide the following:

  - The output produced by 'make pdp11' using the unmodified repo contents.

  - The build command you used that drove you down this path in the first place.

Thanks.

- Mark

**Comment by TentacleMan** [comment] 2016-03-08 19:56
Certainly. Some more fiddling revealed that if I change locale to English, everything works without the need for any changes. Please see the attached build log. The error messages from `gcc` in the beginning is in Swedish but you can probably guess what they say or use Google translate. I can aid in translation if needed too. 

```
[jdoe@unicorn simh]$ uname -a
Linux unicorn 4.4.3-1-ARCH #1 SMP PREEMPT Fri Feb 26 15:09:29 CET 2016 x86_64 GNU/Linux

(*** note: env LANG is now set to sv_SE.UTF-8 ***)

[jdoe@unicorn simh]$ make USE_NETWORK=1 pdp11 2>&1 | tee /tmp/sv_build.txt
lib paths are: /usr/lib/ /usr/lib/ffmpeg2.8/ /usr/lib/libfakeroot/
include paths are: 
using libm: /usr/lib/libm.so
using librt: /usr/lib/librt.so
*** Info ***
*** Info *** The simulator you are building could provide more
*** Info *** functionality if video support were available on your system.
*** Info *** Install the development components of libSDL packaged by your
*** Info *** operating system distribution and rebuild your simulator to
*** Info *** enable this extra functionality.
*** Info ***
*** Warning ***
*** Warning *** pdp11 Simulator are being built WITHOUT
*** Warning *** libpcap networking support
*** Warning ***
*** Warning *** To build simulator(s) with libpcap networking support you
*** Warning *** should read 0readme_ethernet.txt and follow the instructions
*** Warning *** regarding the needed libpcap development components for your
*** Warning *** Linux platform
*** Warning ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should read 0readme_ethernet.txt and follow the instructions
*** Info *** regarding the needed libvdeplug components for your Linux
*** Info *** platform
*** Info ***
*** Warning ***
*** Warning *** pdp11 Simulator are being built WITHOUT LAN networking support
*** Warning ***
*** Warning *** To build simulator(s) with networking support you should read
*** Warning *** 0readme_ethernet.txt and follow the instructions regarding the
*** Warning *** needed libpcap components for your Linux platform
*** Warning ***
***
*** pdp11 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 5.3.0.
*** - WITHOUT Local LAN networking support.
*** - Local LAN packet transports: NAT(SLiRP)
***
*** git commit id is 3a4e879c078ab5080ab5c3d7795daf8c157ea850.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -flto -fwhole-program -Wno-unused-result -DSIM_GIT_COMMIT_ID=3a4e879c078ab5080ab5c3d7795daf8c157ea850 -DSIM_COMPILER="GCC Version: 5.3.0" -I . -D_GNU_SOURCE  sim_BuildROMs.c -o BIN/BuildROMs
BIN/BuildROMs
rm -f BIN/BuildROMs
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -flto -fwhole-program -Wno-unused-result -DSIM_GIT_COMMIT_ID=3a4e879c078ab5080ab5c3d7795daf8c157ea850 -DSIM_COMPILER="GCC Version: 5.3.0" -I . -D_GNU_SOURCE  PDP11/pdp11_fp.c PDP11/pdp11_cpu.c PDP11/pdp11_dz.c PDP11/pdp11_cis.c PDP11/pdp11_lp.c PDP11/pdp11_rk.c PDP11/pdp11_rl.c PDP11/pdp11_rp.c PDP11/pdp11_rx.c PDP11/pdp11_stddev.c PDP11/pdp11_sys.c PDP11/pdp11_tc.c PDP11/pdp11_tm.c PDP11/pdp11_ts.c PDP11/pdp11_io.c PDP11/pdp11_rq.c PDP11/pdp11_tq.c PDP11/pdp11_pclk.c PDP11/pdp11_ry.c PDP11/pdp11_pt.c PDP11/pdp11_hk.c PDP11/pdp11_xq.c PDP11/pdp11_xu.c PDP11/pdp11_vh.c PDP11/pdp11_rh.c PDP11/pdp11_tu.c PDP11/pdp11_cpumod.c PDP11/pdp11_cr.c PDP11/pdp11_rf.c PDP11/pdp11_dl.c PDP11/pdp11_ta.c PDP11/pdp11_rc.c PDP11/pdp11_kg.c PDP11/pdp11_ke.c PDP11/pdp11_dc.c PDP11/pdp11_dmc.c PDP11/pdp11_kmc.c PDP11/pdp11_dup.c PDP11/pdp11_rs.c PDP11/pdp11_vt.c PDP11/pdp11_td.c PDP11/pdp11_io_lib.c   scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c -DVM_PDP11 -I PDP11 -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DUSE_NETWORK  -o BIN/pdp11 -lm -lrt   -flto -fwhole-program
slirp_glue/sim_slirp.c: I funktion ”sim_slirp_open”:
slirp_glue/sim_slirp.c:325:5: varning: implicit deklaration av funktionen ”pthread_mutex_init” [-Wimplicit-function-declaration]
     pthread_mutex_init (&slirp->write_buffer_lock, NULL);
     ^
slirp_glue/sim_slirp.c: I funktion ”sim_slirp_close”:
slirp_glue/sim_slirp.c:381:5: varning: implicit deklaration av funktionen ”pthread_mutex_destroy” [-Wimplicit-function-declaration]
     pthread_mutex_destroy (&slirp->write_buffer_lock);
     ^
slirp_glue/sim_slirp.c: I funktion ”sim_slirp_send”:
slirp_glue/sim_slirp.c:441:1: varning: implicit deklaration av funktionen ”pthread_mutex_lock” [-Wimplicit-function-declaration]
 pthread_mutex_lock (&slirp->write_buffer_lock);
 ^
slirp_glue/sim_slirp.c:444:1: varning: implicit deklaration av funktionen ”pthread_mutex_unlock” [-Wimplicit-function-declaration]
 pthread_mutex_unlock (&slirp->write_buffer_lock);
 ^
/usr/bin/ld: /tmp/ccpurNVe.ltrans19.ltrans.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: fel: ld returnerade avslutningsstatus 1
makefile:1432: receptet för målet ”BIN/pdp11” misslyckades
make: *** [BIN/pdp11] Fel 1
[jdoe@unicorn simh]$ make clean
lib paths are: /usr/lib/ /usr/lib/ffmpeg2.8/ /usr/lib/libfakeroot/
include paths are: 
using libm: /usr/lib/libm.so
using librt: /usr/lib/librt.so
rm -f -r BIN/

(*** ... but if I change LANG to English ***)

[jdoe@unicorn simh]$ export LANG=en_US.UTF-8
[jdoe@unicorn simh]$ make pdp11 2>&1 | tee /tmp/en_build.txt
lib paths are: /usr/lib/ /usr/lib/ffmpeg2.8/ /usr/lib/libfakeroot/
include paths are:  /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include /usr/local/include /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed /usr/include
using libm: /usr/lib/libm.so
using librt: /usr/lib/librt.so
using libpthread: /usr/lib/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib/libpcreposix.so /usr/include/pcreposix.h
using libdl: /usr/lib/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/libpng.so /usr/include/png.h
using mman: /usr/include/sys/mman.h
using libSDL2: /usr/lib/libSDL2.so /usr/include/SDL2/SDL.h
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/lib/libvdeplug.so /usr/include/libvdeplug.h
***
*** pdp11 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 5.3.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
***
*** git commit id is 3a4e879c078ab5080ab5c3d7795daf8c157ea850.
***
mkdir -p BIN
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -flto -fwhole-program -Wno-unused-result -DSIM_GIT_COMMIT_ID=3a4e879c078ab5080ab5c3d7795daf8c157ea850 -DSIM_COMPILER="GCC Version: 5.3.0" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  sim_BuildROMs.c -o BIN/BuildROMs
BIN/BuildROMs
rm -f BIN/BuildROMs
mkdir -p BIN
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -flto -fwhole-program -Wno-unused-result -DSIM_GIT_COMMIT_ID=3a4e879c078ab5080ab5c3d7795daf8c157ea850 -DSIM_COMPILER="GCC Version: 5.3.0" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_LIBPNG -DHAVE_GLOB -DHAVE_SHM_OPEN  PDP11/pdp11_fp.c PDP11/pdp11_cpu.c PDP11/pdp11_dz.c PDP11/pdp11_cis.c PDP11/pdp11_lp.c PDP11/pdp11_rk.c PDP11/pdp11_rl.c PDP11/pdp11_rp.c PDP11/pdp11_rx.c PDP11/pdp11_stddev.c PDP11/pdp11_sys.c PDP11/pdp11_tc.c PDP11/pdp11_tm.c PDP11/pdp11_ts.c PDP11/pdp11_io.c PDP11/pdp11_rq.c PDP11/pdp11_tq.c PDP11/pdp11_pclk.c PDP11/pdp11_ry.c PDP11/pdp11_pt.c PDP11/pdp11_hk.c PDP11/pdp11_xq.c PDP11/pdp11_xu.c PDP11/pdp11_vh.c PDP11/pdp11_rh.c PDP11/pdp11_tu.c PDP11/pdp11_cpumod.c PDP11/pdp11_cr.c PDP11/pdp11_rf.c PDP11/pdp11_dl.c PDP11/pdp11_ta.c PDP11/pdp11_rc.c PDP11/pdp11_kg.c PDP11/pdp11_ke.c PDP11/pdp11_dc.c PDP11/pdp11_dmc.c PDP11/pdp11_kmc.c PDP11/pdp11_dup.c PDP11/pdp11_rs.c PDP11/pdp11_vt.c PDP11/pdp11_td.c PDP11/pdp11_io_lib.c display/display.c display/sim_ws.c display/vt11.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c -DVM_PDP11 -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_VDE_NETWORK -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -DUSE_DISPLAY -DHAVE_LIBSDL -DUSE_SIM_VIDEO -I/usr/include/SDL2/ -lSDL2 -o BIN/pdp11 -lm -lrt -lpthread -lpcreposix -ldl -lpng -lvdeplug -Wl,-R,/usr/lib/ -L/usr/lib/  -flto -fwhole-program
[jdoe@unicorn simh]$ file BIN/pdp11
BIN/pdp11: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=ff7e52972081821328ecd985e3ac3f3b6e8584b6, not stripped
[jdoe@unicorn simh]$ 
```

**Comment by markpizz** [comment] 2016-03-08 20:06
Well, the two make commands are different.  Do you get the same result without the USE_NETWORK=1?

Presuming the answer is yes, can you point me to where I can download this Linux distribution so I can repro this in a local VM?

**Comment by TentacleMan** [comment] 2016-03-08 20:23
Yes, the result is the same. With Swedish locale I get no network with or without USE_NETWORK=1 and the build crashes as displayed above. The distro is Archbang x86_64 that you can find here:
https://sourceforge.net/projects/archbang/files/
Main site: http://bbs.archbang.org/
I installed from an earlier iso image from last fall, don't remember the exact date but I have been updating all packages regularly so they should be current.

**Comment by markpizz** [comment] 2016-03-08 21:56
Now that you have identified what you are seeing as being related to language, AND the output produced by the build has the line:

> include paths are: 

I think I see that the problem is in this line in the makefile:

>  INCPATH:=$(shell $(GCC) -x c -v -E /dev/null 2>&1 | grep -A 10 '> search starts here' | grep '^ ' | tr -d '\n')

It would seem that 'search starts here' is not the proper string to be looking for...

I quickly tried to install the archbang Linux from the latest iso. The ISO boots, but when I try to follow the install instructions at: http://wiki.archbang.org/index.php?title=ArchBang_Document it is not obvious how to get off the ground.

Alternatively I created a new VM installed Ubuntu 15.10 with Spanish as the language (I might be able to stumble through reading a little spanish).  I was able to build just fine with the Ubuntu Linux version.  the output of the gcc command in the above INCPATH command actually does contain 'search starts here' in English.

Suggestions as to how to start the Arch Linux installation with a brand new disk???

My goal will be to see if the makefile can be tweaked to force a definition of LANG=en_US.UTF-8 so the INCPATH assignment has the correct string in the output...

**Comment by larsbrinkhoff** [comment] 2016-03-09 07:49
Obviously, looking for `search starts here` doesn't work if that string is translated.

Here is part of gcc that is responsible for the output:
https://github.com/gcc-mirror/gcc/blob/bd3f0a53c07086e978ea4ec00e10a20e4a969c40/gcc/incpath.c#L373

Here are all the translations:
https://github.com/gcc-mirror/gcc/tree/master/gcc/po

E.g. the Swedish translation is `#include <...> sökning startar här:`

Maybe looking for `#include <` or `#include "` would work?

**Comment by markpizz** [comment] 2016-03-09 18:04
Lars,

Thanks for finding the underlying translation activities.  

Now that the locale language has been identified as something which can influence the build behavior, AND @TentacleMan so nicely found the workaround of running with LANG defined so that the expected search string will be found, I'd prefer to try and force the language to be aligned with what the makefile expects (throughout), rather than in the case of this specific text string.  There are already other language specific string searches.

Apart from properly evaluating details about the local system environment in the makefile, the original complaint about needing to "include <pthread.h>" actually illuminates another problem.  This problem is the fact that there may be some environments which don't actually have pthreads available, but may still be capable of using NAT(slirp) for network transport.

Both of these are now fixed.

Please re-open this issue if someone believes this not to be true.

Thanks.

- Mark

**Closed** 2016-03-09 18:05 UTC
