### ISSUE TITLE
VAX pasting more then about 5 lines text on the console results in buffer overrun

### ISSUE THREAD

**Issue by mike632t** [simh/simh#585] opened 2018-06-01 00:45 UTC
When using a recent verson of the VAX simulator (commit id 0fa5807) pasting a block of text into a EDIT/TPU session in the console window results in a buffer overrun after about 5 lines...

I seem to remember that this has come up before but couldn't find the issue.

It would be really useful to be able to past large blocks of text into the editor reliably using the console or an emulated serial device using telnet (VH or DZ) - currently I'm using KERMIT to transfer files.

```

/*
 * x11-window.c
 *
 * Displays a window on the screen.
 *

[End of file]















 Buffer: X11-WINDOW.C                                                                    
Data overrun
```
Compiled with gcc version 4.9.2 (Debian 4.9.2-10+deb8u1) using 'make vax' with libpcap and libsdl.

```
$ make vax
lib paths are: /lib/ /lib/x86_64-linux-gnu/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/lib/x86_64-linux-gnu/tls/
include paths are: /usr/lib/gcc/x86_64-linux-gnu/4.9/include /usr/local/include /usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed /usr/include/x86_64-linux-gnu /usr/include
using libm: /usr/lib/x86_64-linux-gnu/libm.so
using librt: /usr/lib/x86_64-linux-gnu/librt.so
using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib/x86_64-linux-gnu/libpcreposix.so /usr/lib/x86_64-linux-gnu/libpcre.so /usr/include/pcreposix.h /usr/include/pcre.h
using libdl: /usr/lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
using mman: /usr/include/x86_64-linux-gnu/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
using libpcap: /usr/include/pcap.h
*** Info ***
*** Info *** vax Simulator are being built with
*** Info *** minimal libpcap networking support
*** Info ***
*** Info ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should install the vde2 package to provide this
*** Info *** functionality for your Linux system:
*** Info *** $ sudo apt-get install libvdeplug-dev
*** Info ***

*** vax Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 4.9.2.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).

*** git commit id is 0fa5807.
*** git commit time is 2018-05-28T11:58:42-07:00.

gcc -std=gnu99 -U__STRICT_ANSI__ -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=0fa5807e1dae435c129b9e94a09f89f6bff3775d -DSIM_GIT_COMMIT_TIME=2018-05-28T11:58:42-07:00 -DSIM_COMPILER="GCC Version: 4.9.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO -DHAVE_PCREPOSIX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_GLOB -DHAVE_SHM_OPEN sim_BuildROMs.c -o BIN/BuildROMs
BIN/BuildROMs
rm -f BIN/BuildROMs
gcc -std=gnu99 -U__STRICT_ANSI__ -O2 -finline-functions -fgcse-after-reload -fpredictive-commoning -fipa-cp-clone -fno-unsafe-loop-optimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=0fa5807e1dae435c129b9e94a09f89f6bff3775d -DSIM_GIT_COMMIT_TIME=2018-05-28T11:58:42-07:00 -DSIM_COMPILER="GCC Version: 4.9.2" -I . -D_GNU_SOURCE -DUSE_READER_THREAD -DSIM_ASYNCH_IO -DHAVE_PCREPOSIX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_GLOB -DHAVE_SHM_OPEN VAX/vax_cpu.c VAX/vax_cpu1.c VAX/vax_fpa.c VAX/vax_io.c VAX/vax_cis.c VAX/vax_octa.c VAX/vax_cmode.c VAX/vax_mmu.c VAX/vax_stddev.c VAX/vax_sysdev.c VAX/vax_sys.c VAX/vax_syscm.c VAX/vax_syslist.c VAX/vax_vc.c VAX/vax_lk.c VAX/vax_vs.c VAX/vax_2681.c PDP11/pdp11_rl.c PDP11/pdp11_rq.c PDP11/pdp11_ts.c PDP11/pdp11_dz.c PDP11/pdp11_lp.c PDP11/pdp11_tq.c PDP11/pdp11_xq.c PDP11/pdp11_vh.c PDP11/pdp11_cr.c PDP11/pdp11_td.c PDP11/pdp11_io_lib.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -DVM_VAX -DUSE_INT64 -DUSE_ADDR64 -DUSE_SIM_VIDEO -I VAX -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_TAP_NETWORK -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/.c slirp_glue/.c -DHAVE_LIBSDL -DUSE_SIM_VIDEO /usr/bin/sdl2-config --cflags /usr/bin/sdl2-config --libs -o BIN/microvax3900 -lm -lrt -lpthread -lpcreposix -lpcre -ldl
cp BIN/microvax3900 BIN/vax
$
```

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment] 2018-06-01 00:50
Most of the simulators (the DEC ones at least) will comfortably accept pasted text into the console window and the simh framework layer will not over-run things.

Meanwhile, the operating system running within the simulator may not be able to dispatch the received data to a user mode program BEFORE the OS's device 'type ahead' buffer is over run.  Various VMS sysgen parameters can be adjusted to influence this.

- Mark

**Comment by mike632t** [comment] 2018-06-01 01:08
Thanks,
I suspect that means I need to increase MIN_TTY_TYPAHDSZ, and MIN_TTY_ALTYPAHD

**Comment by markpizz** [comment] 2018-06-01 01:15
Make them BIG (32768) and you should see different results.

**Comment by mike632t** [comment] 2018-06-01 15:48
That is _very_ big, but I guess I do have 16M RAM these days!
Currently set at 2046 (I think this was the recommended setting when using Kermit) - I'll increase them later do some testing and post the results here

Thanks

**Comment by markpizz** [comment] 2018-06-01 16:09
It is a much bigger number than the defaults, but as you observe it is trivial compared to the memory available in the system (16MB on a MicroVAX II simulator and 512MB on a MicroVAX 3900).  That number is consumed per serial port device on the system (the console plus each DZ or VH line).  Still not much, but it is there.

In the kermit case, the kermit protocol actively handshakes data flow so there is a reasonable limit.  Merely pasting into a terminal session has no handshaking going on, so you might need a typeahead buffer that is as big as your largest expected paste.

**Comment by markpizz** [comment] 2018-06-06 17:37
Please close this issue when you've confirmed that changing simulated OS SYSGEN settings affects the behavior and the problem isn't in the simulator itself.

**Comment by mike632t** [comment] 2018-06-06 21:38
When using a recent version of simh (commit 0fa5807e) I found that increasing the size of TTY_TYPAHDSZ and TTY_ALTYPAHD did as allow me to to paste much larger blocks of text when using CREATE/FILE.

However I have also noticed that with this version when using telnet to connect to a VH device output characters are being 'lost'.  For example if I execute SH TERM...
```
$ SH TERM
Terminal: _TXA1:      Device_Type: VT100         Owner: USER

   Input:   9600      LFfill:  0      Width:  80      Parity: None
   Output:  9600      CRfill:  0      Page:   24      

Terminal Characteristics:
   Interactive        Echo               Type_ahead         No Escape
   No Hostsync        TTsync             Lowercase          Tab
   Wrap               Scope              No Remote          No Eightbit



```
Not even the  prompt is shown until I press press <CR>.

I found that this problem occurs regardless whether or not I increase TTY_TYPAHDSZ and TTY_ALTYPAHD.


I'm not sure if it helps but when using an earlier version of simh (commit 18175040) increasing TTY_TYPAHDSZ and TTY_ALTYPAHD didn't make any difference when pasting in text.

```
$ CREATE X11-WINDOW.C;
/*
 * x11-window.c
 *
 * Displays a window on the screen.
 *
 * This  program is free software: you can redistribute it and/or modify  it
 * under  the  terms of the GNU General Public License as published  by  the
 * Free  Software  Foundation, either version 3 of the License, or (at  your
 * option) any later version.
 *
 * This  program  is  distributed in the hope that it will  be  useful,  but
 * WITHOUT   ANY   WARRANTY;   without  even   the   implied   warranty   of
 * MERCHAN
%CREATE-E-READERR, error reading SYS$INPUT:.;
-RMS-F-RER, file read error
-SYSTEM-W-DATAOVERUN, data overrun
$ TABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
%DCL-W-IVVERB, unrecognized command verb - check validity and spelling
 \TABILITY\
```
However I don't have any problems with output characters being lost.

**Comment by markpizz** [comment] 2018-06-06 21:52
The VH problem was reported yesterday in #588 .  Feel free to watch or add to the discussion there.

> I'm not sure if it helps but when using an earlier version of simh (commit 1817504052) ...

Commit 1817504052 was 3.5 years ago.  A ridiculous number of changes have occurred since then.  What usually might be helpful would be to use "git bisect" to identify a particular commit that introduced some errant behavior.  Don't worry about that for this case though.

I'm closing this issue here now.  If you feel inspired, please test on a DZ line using the same OS disk and only if that doesn't work reopen the issue.  You can confirm the VH case once the VH output issue is fixed in #588

**Closed by markpizz** 2018-06-06 21:52 UTC

**Comment by sqkeith** [comment] 2018-06-06 22:00
With SIMH 3.9, I used putty to paste the entire vms hobbyist licence file into an EVE edit session without any problem at all, though putty does allow you to set the paste-in rate so maybe that helped... without adjusting those sysgen buffer parameters.

**Comment by markpizz** [comment] 2018-06-06 22:13
SIMH 3.9 came out more than 6 years ago, and there have been MANY changes in the console and MUX domain to make their behaviors more closely reflect real hardware.  As a result, I don't recall exactly why that might have worked.  I vaguely recall that there may have been some interaction with idling that unintentionally limited console input processing and thus avoided the OS typeahead buffer overruns that were observed here.  A good number of other issues have been raised AND solved that, like I said, let simulated MUX devices behave like real hardware.
