### ISSUE TITLE
PDP10 timer problem (issue #108 reversion)

### ISSUE THREAD

**Issue by davygoat** [simh/simh#699] opened 2019-05-06 17:52 UTC
**Provide a general summary of the issue in the Title above**

I'm running TOPS-10 7.04 under the PDP10 simulator. When I submit a simple batch control file, it aborts with a "Time limit exceeded" message.

**Provide a more detailed introduction to the issue itself, and why you consider it to be a bug or why the suggested change or enhancement would be useful**

The same problem was first reported by Jordi Guillaumes Pons in 2014 (issue #108). I've done a git checkout out that of commit (897491deead99a718166e45524900b7647f38c92), and that works as expected. I've also done a git bisect, with the following result:

```
e36873f46686699b6fc4dee89d7e5233d6a71894 is the first bad commit
commit e36873f46686699b6fc4dee89d7e5233d6a71894
Author: Mark Pizzolato <mark@infocomm.com>
Date:   Wed Jan 18 23:53:46 2017 -0800

    TIMER: Fix coscheduling functionality to produce consistent results

    Added debug CHECK option to the sim_timer_activate_after() to verify
    that coscheduled events actually have sim_activate_time_usecs() results
    which are consistent with each other.
    Additionally, coschedule tick processing now properly counts down
    pending coschedule queued activities.

:100644 100644 ae81ec23df5b2344f1a9e596c754f846f31b51e0 855090d3b69c3c2ab91b6a2c5fb01087dd07728a M      scp.c
:100644 100644 15f5092ac42d160e9c2f7068e8a4908e09089e10 7cb0814e078493e1071730c45b7e440ed14abed5 M      scp.h
:100644 100644 df6f4dde09c7158edaf228eb76e61aa5b4950023 f789173972ffe8a9fa2db3132d96ed5fd04b46c3 M      sim_timer.c
:100644 100644 4a72d68670454579cd57879bbd1c24d9061335c0 c447d78619f9df528e4d3a6e5fd2665067669a9f M      sim_timer.h
```

**The output of "sim> SHOW VERSION" while running the simulator which is having the issue**

```
PDP-10 simulator V4.0-0 Current        git commit id: 287655da
sim> sh ver
PDP-10 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 5.5.0
        Simulator Compiled as C arch: x64 (Release Build) on May  6 2019 at 18:01:01
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux slackware 4.4.172 #2 SMP Wed Jan 30 17:11:07 CST 2019 x86_64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz GenuineIntel GNU/Linux
        git commit id: 287655da
        git commit time: 2019-05-04T14:12:42-0700
sim> 
```

**How you built the simulator or that you're using prebuilt binaries**

git clone, make pdp10

```
[david@slackware ~/simh/src/simh]$ make pdp10
lib paths are: /lib64/ /usr/lib64/
include paths are:  /usr/lib64/gcc/x86_64-slackware-linux/5.5.0/include /usr/loc.0/include-fixed /usr/include
using libm: /usr/lib64/libm.so
using librt: /usr/lib64/librt.so
using libpthread: /usr/lib64/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib64/libpcreposix.so /usr/lib64/libpcre.so /usr/includ
using semaphore: /usr/include/semaphore.h
using libdl: /usr/lib64/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib64/libpng.so /usr/include/png.h
using mman: /usr/include/sys/mman.h
using libpcap: /usr/include/pcap.h
*** Info ***
*** Info *** pdp10 Simulator is being built with
*** Info *** minimal libpcap networking support
*** Info ***
*** Info ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should read 0readme_ethernet.txt and follow the instructions
*** Info *** regarding the needed libvdeplug components for your Linux
*** Info *** platform
*** Info ***
***
*** pdp10 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 5.5.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - Per simulator tests will be run.
***
*** git commit id is 287655da92789266ccdfea625b508b7d2e84c7d4.
*** git commit time is 2019-05-04T14:12:42-0700.
***
gcc -std=gnu99 -U__STRICT_ANSI__  -O2 -finline-functions -fgcse-after-reload -fpoptimizations -fno-strict-overflow -Wno-unused-result -DSIM_GIT_COMMIT_ID=287655TIME=2019-05-04T14:12:42-0700  -DSIM_COMPILER="GCC Version: 5.5.0" -I . -D_GNU_SREPOSIX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so EN  PDP10/pdp10_fe.c PDP11/pdp11_dz.c PDP10/pdp10_cpu.c PDP10/pdp10_ksio.c PDP10DP10/pdp10_rp.c PDP10/pdp10_sys.c PDP10/pdp10_tim.c PDP10/pdp10_tu.c PDP10/pdp101_cr.c PDP11/pdp11_dup.c PDP11/pdp11_dmc.c PDP11/pdp11_kmc.c PDP11/pdp11_xu.c PDer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_vi PDP10 -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHAglue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -dl -lpng  
```

**The simulator configuration file (or commands) which were used when the problem occurred.**

```
attach rp0 704/dskb.dsk
attach rp1 704/dskc.dsk

set lp20 enable
delete 704/printer.out
attach lp20 704/printer.out

set dz 8b
attach -am dz 2020

set tim y2k
set cpu tops10
set cpu idle

boot rp
```

**The expected behavior and the actual behavior**

Following messages are displayed on the operator console. Expected behaviour is to show just begin/end messages, without intervening "Time limit exceeded". TOPS-10 7.03 does not have this problem with the current simh.

```
18:06:52        Batch-Stream 0  -- Begin --
                Job DELME Req #32 for DAVID [42,42]
                Control file: DSKC:DELME.CTL[42,42]
                Log file:     DSKC:DELME.LOG[42,42]
OPR>
18:06:53        Batch-Stream 0  -- Batch error --
                Job DELME Req #32 for DAVID [42,42]
                Time limit exceeded; end of control file while searching for lab
el %TERR

18:06:53        Batch-Stream 0  -- End --
                Job DELME Req #32 for DAVID [42,42]
```

**You may also need to provide specific pointers to data files that may be necessary to demonstrate the problem**

Create a simple batch control file, DELME.CTL, containing three DIR commands.

```
.copy delme.ctl=tt:
.dir sys:
.dir sys:
.dir sys:
^Z
.submit delme
```

Issue #108 had a program to show time remaining.

**Comment by markpizz** [comment] 2019-05-06 20:18
@davygoat Please put your name on your GitHub profile.

As for the problem here, please provide pointers to somewhere I can pickup the disk images you're using.

I will need detailed session instructions regarding how to respond when the simulator boots before creating or initiating the delme.ctl script.  It would be fantastic if you could provide a configuration file that both boots and responds to the initial system prompts (with simh EXPECT and SEND commands) to get to the point where you can submit the delme.ctl file.

**Comment by davygoat** [comment] 2019-05-07 07:42
OK. Give me a day or two to figure it out.

David.

**Comment by davygoat** [comment] 2019-05-07 19:26
Hello Mark,


Turns out I already had Google Drive available to use. Here is the link.

https://drive.google.com/open?id=17GLv0XBnWa4_zGlzjA09yBcxI_ye6kcO


- The file is an xz compressed tarball (35MB). Uncompress with "tar -xJvf" (capital J), or "xz -d" followed by "tar -xvf".

- The TOPS-10 7.04 installation is a bog standard install from the Monitor Installation Guide (h/t Quentin North's blog).

- Start the simulation/test by typing "./pdp10 problem.ini". I've included the latest pdp10 binary for Linux.

- Boot prompts are handled automatically by simh expect/send.

- Then it proceeds automatically to exit OPR, and SUBMIT the file TEST.CTL. The /NOTIFY option lets you know when it's finished. The /BATLOG:SUPERSEDE option tells it to replace the log file rather than append to it. The /OUTPUT:NOLOG option tells it not to send the log to the printer. /TIME:24:00:00 gives it "plenty time to spare".

- The job will abort with reason "Time limit exceeded". Expected behaviour is say "finished executing" and produce a much larger log file. (Do not add a %TERR label to TEST.CTL. If you do, it still runs out of time, but you won't see the error message without "TYPE TEST.LOG" or having to go back into R OPR.)

- To see the log, "TYPE TEST.LOG". I'm not sure if the times (produced by the batch system) are wall times or CPU times. If you want to see the actual "time remaining" counter, issue #108 had a Fortran program that someone wrote for that purpose.

- To run the submit command again, type "DO TEST", which runs a MIC script to save you having to type the whole submit thing again.

- To perform a clean shutdown, type "DO SHUTDOWN". The init script automatically exits simh when it sees the final "KSYS processing completed" message.


Hope this helps,
David.

**Comment by markpizz** [comment] 2019-05-29 07:46
Hi David,

I've been digging into what is going on here.  

***Thanks for the precise setup to reproduce the problem!***


Do you have access to the source code, explicitly for this version of the operating system for the driver which interfaces to the interval timing hardware?  I recall that some operating systems using this hardware had code that attempted to adjust the size of the programmed interval (once per second as I recall) to avoid tick drift due to the frequency of the available interval timer not being precisely divisible by 60.   What I'm seeing with this OS is the interval value switching back and forth between ticks at 59 hz and 63 hz on every other tick.  As it turns out, simh is completely capable of providing an interval timer based clock mechanism (which this uses), however it needs something that acts as a consistent interval timer in order to properly calibrate consistent intervals.  The fact that this OS is frequently messing with the tick rate interferes with the simulator framework properly measuring the simulator's instruction execution rate (aka calibration) and thus how it provides the underlying timing services.  There were problems in earlier simulator versions where some simulators had multiple separate interval timers.  If each of these were used at the same time (operating at different tick frequencies) and the framework tried to calibrate the execution rate with both running simultaneously there were confused results.  A change was made to address this situation so that only the fastest ticking calibrated clock actually performed the calibration computation and the slower ticking clock used the calibration results from the faster clock.  This now works well and even tolerates the case when none of these clock devices is running.  When there are no clocks performing calibration activities, the simulation framework detects this and it runs an internal clock at 10 Hz which is calibrated against the instruction execution rate and any devices which engage wall clock delays (with sim_activate_after()) will function correctly.  The constant switching between different tick rates with this device ends up disabling calibration since instruction rate calibration only happens after simulation has been running for at least a second.

To address this problem with this device, I've changed the programmatic interval timer device TIM to no longer declare itself as a calibrated timer, and to no longer engage the calibration APIs.  With no specific calibrated timer provided by the simulator itself, the internal timer will now run to provide the precise timing services required.  This problem illuminated the need for the internal timer to actually run at tick rate which is the MAX(100,Host_OS_tick_size), which it now does.

Please try the latest code.

- Mark

**Comment by davygoat** [comment] 2019-05-30 07:46
Hello Mark,

Thank you, the latest code does indeed fix the batch problem. But if you type "day" every five or ten minutes, you'll find the clock is also losing time. I was going to wait until I could observe it running for a few hours. But it seems another user (#705) is also affected on vax now.

"Do you have access to the source code, explicitly for this version of the operating system for the driver which interfaces to the interval timing hardware?"

The monitor sources are in [10,7,MON], possibly CLOCK1.MAC. (I only have the most rudimentary understanding of assembly, sorry.)

David.

**Comment by davygoat** [comment] 2019-05-30 07:47
Sorry, I pressed "Close and comment" instead of "Comment".

**Comment by markpizz** [comment] 2019-05-30 10:25
Give the latest a try.  The fix for the PDP10 was unrelated to the problem the VAX simulator that others were seeing.

**Comment by davygoat** [comment] 2019-06-03 18:21
I kept an eye on 564ce2b over the weekend but got the impression the clock was running slightly fast. So I did another git pull yesterday, just to make sure, because I noticed there were some timer related updates.

It gains almost exactly 15 minutes over 24 hours.

**Comment by davygoat** [comment] 2019-06-09 19:25
Hello Mark,

Commit 53ad66f5 runs considerably better now. But it still runs about 2 minutes fast after 24 hours.

Incidentally, TOPS-10 7.03 does not. It seems to stay pretty close to the host clock.

Do you want to pursue this further? Or is 704 a lost cause on KS? (704 has the more painful "doing a sub mic" problem that I queried on the mailing list.)

David.

**Comment by markpizz** [comment] 2019-06-09 21:48
Hi David,

120 seconds in 24 hours is 5 seconds per hour.  I'm definitely not seeing that on Windows or a Raspberry Pi with the latest commit (after 53ad66f57ebdec051d3345d5957a69707ddc3e32).   I'm not exactly sure what you mean by "doing a sub mic"???

- Mark

**Comment by davygoat** [comment] 2019-06-12 18:19
Hello Mark,


It's down to about 20 seconds now (8c4f8b0b), again over 24 hours.


The "doing a sub mic problem", as I call it, goes as follows:

- Create two mic scripts. One invokes the other.

```
MAIN.MIC

.do sub

SUB.MIC

.dir
```
- DO main.
- Error message "?Illegal memory reference at user PC 401777", and returns to the monitor prompt.
- Any further attempts to to DO any mic script, in any job, will cause the job to spin.
- Ctrl/C does not work. The job can be killed with the MEAN option (R KILL, then KILL 3[42,42] MEAN).
- Should I raise a separate issue for this one?

David.

**Comment by markpizz** [comment] 2019-06-13 15:47
Hi Dave,

If you compare the simulator time vs wall clock while idling is enabled vs when it is not enabled, you should find that when it is not enabled it is very precise and somewhat less so with idling enabled (your observed 20 sec in 24 hours).  I suspect that this will vary depending on the OS version that is running in the simulator and how that OS uses the simulator's TIM device to keep time.  I'm still working on a few things which might or might not improve the behavior while idling further.  Please leave this issue open while I'm doing that.  Meanwhile, it certainly isn't the slightest bit clear that the "sub mic problem" has anything to do with timing, so please create a new issue for that problem.

Thanks.

Mark

**Comment by markpizz** [comment] 2019-07-11 13:04
The timing behaviors in the framework have been stable from my point of view.  Are you happy with things using the latest code?  If so, please close this issue.

**Closed** 2019-07-11 15:31 UTC
