### ISSUE TITLE
SimH halts on I/O error, but should not

### ISSUE THREAD

**Issue by tlhackque** [simh/simh#533] opened 2018-02-24 16:57 UTC
#### Summary:

A VAX 3900 simulator, without admin privs under windows 10, halts the simulation with an I/O error when a physical CDROM is attached, but empty on boot, and subsequently accessed from VMS.

The simulation should continue, and return a suitable error status to VMS.

Halting the simulation is an inappropriate response to a device error.

#### Details:

Host: Notebook PC, Windows 10 Pro (details below).

The simulator is run without admin privs (the OpenVPN tap config allows network access w/o rights).  This will turn out to be the trigger for the error.

VMS is V7.3, new ootb installation - nothing special about its configuration.

SimH is (as of yesterday), the latest prebuilt Windows binary.

````
MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c4e55d0f
sim> show ver
MicroVAX 3900 simulator V4.0-0 Beta
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Jan 12 2018 at 15:14:35
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.5
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.16299.248]
        Architecture: x86 on AMD64, Processors: 8
        Processor Id: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel, Level: 6, Revision: 3c03
        git commit id: c4e55d0f
````
#### Init file
````
; Initialization file for VAX
;set cpu extend
set cpu 256m
;set romdelay
attach NVR ka655.nvr
set lpt disable
set rl disable
;set ry disable
set ts disable
set vh disable
set rq0 enable
set rq0 ra92
attach rq0 -e vms0873.simh_dsk
set rq1 enable
set rq1 rrd40
attach rq1 -f raw //./cdrom0
attach xq SimH Virtual Network
set dz lines=16
echo User lines on telnet port 210
attach -am dz 210
set cpu conhalt
set console brk=10
echo Switching console to telnet port 200
set console telnet=200
b cpu
````
#### Starting emulator (CMD window)
````
Desktop\SimH>vax vms.ini

MicroVAX 3900 simulator V4.0-0 Beta        git commit id: c4e55d0f
vms.ini-5> attach NVR ka655.nvr
NVR: buffering file in memory
RQ0: 'vms0873.simh_dsk' Contains ODS2 File system
RQ0: Volume Name: VAXVMSSYS073 Format: DECFILE11B   Sectors In Volume: 2940951
Device OK - Type: CD_ROM, Number: 0
Removable Device
WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Eth: opened OS device \Device\NPF_{68468055-D2C0-432A-81E7-22EAE447C436} - SimH Virtual Network
User lines on telnet port 210
vms.ini-20> attach -am dz 210
Listening on port 210
Modem control activated
Auto disconnect activated
Switching console to telnet port 200
vms.ini-24> set console telnet=200
Listening on port 200
Loading boot code from internal ka655x.bin
Waiting for console Telnet connection
Waiting for console Telnet connection
````
#### Continue in Console TELNET window

Normal startup (opcom noise omitted)
````
KA655X-B V5.3, VMB 2.7
Performing normal system tests.
40..39..38..37..36..35..34..33..32..31..30..29..28..27..26..25..
24..23..22..21..20..19..18..17..16..15..14..13..12..11..10..09..
08..07..06..05..04..03..
Tests completed.
>>>b
(BOOT/R5:0 DUA0



  2..
-DUA0
  1..0..


%SYSBOOT-I-SYSBOOT Mapping the SYSDUMP.DMP on the System Disk
%SYSBOOT-I-SYSBOOT SYSDUMP.DMP on System Disk successfully mapped
%SYSBOOT-I-SYSBOOT Mapping PAGEFILE.SYS on the System Disk
%SYSBOOT-I-SYSBOOT SAVEDUMP parameter not set to protect the PAGEFILE.SYS
   OpenVMS (TM) VAX Version V7.3     Major version id = 1 Minor version id = 0
%DECnet-I-LOADED, network base image loaded, version = 05.0E.00
%WBM-I-WBMINFO Write Bitmap has successfully completed initialization.
$!  Copyright 2001 Compaq Computer Corporation.

%STDRV-I-STARTUP, OpenVMS startup begun at 24-FEB-2018 11:20:27.45

...[Snip]

%STARTUP-I-AUDITCONTINUE, audit server initialization complete

The OpenVMS VAX system is now executing the site-specific startup commands.

%SET-I-INTSET, login interactive limit = 64, current interactive value = 0
  SYSTEM       job terminated at 24-FEB-2018 11:20:47.62

  Accounting information:
  Buffered I/O count:            2777         Peak working set size:    1654
  Direct I/O count:               870         Peak page file size:     37781
  Page faults:                  22839         Mounted volumes:             0
  Charged CPU time:           0 00:00:09.41   Elapsed time:     0 00:00:20.21

 Welcome to OpenVMS (TM) VAX Operating System, Version V7.3

Username: system
Password:
%LICENSE-I-NOLICENSE, no license is active for this software product
%LOGIN-S-LOGOPRCON, login allowed from OPA0:
 Welcome to OpenVMS (TM) VAX Operating System, Version V7.3 on node HERO
    Last interactive login on Friday, 23-FEB-2018 16:35

$ mount /over=id dua1:
%%%%%%%%%%%  OPCOM  24-FEB-2018 11:22:14.85  %%%%%%%%%%%
Message from user SYSTEM on HERO
medium is offline

%MOUNT-I-OPRQST, medium is offline
%%%%%%%%%%%  OPCOM  24-FEB-2018 11:22:14.86  %%%%%%%%%%%
Request 1, from user SYSTEM on HERO
Please mount device _HERO$DUA1:

````

#### This on the (non-TELNET) console window:

````
Waiting for console Telnet connection
Running
Device OK - Type: CD_ROM, Number: 0
Removable Device
Device OK - Type: CD_ROM, Number: 0
Removable Device
Device OK - Type: CD_ROM, Number: 0
Removable Device
Device OK - Type: CD_ROM, Number: 0
Removable Device
Device OK - Type: CD_ROM, Number: 0
Removable Device
Device OK - Type: CD_ROM, Number: 0
Removable Device
Device OK - Type: CD_ROM, Number: 0
Removable Device
Device OK - Type: CD_ROM, Number: 0
Removable Device
RQ I/O error: Permission denied
RQ1 RQ I/O error: Permission denied
vms.ini-25> b cpu

I/O error, PC: 8E8A1136 (ASHL #1,R3,R0)
sim>
````

#### It is not possible to continue:
````
sim> c
RQ I/O error: Permission denied
RQ1 RQ I/O error: Permission denied

I/O error, PC: 8E8A1134 (CLRL R6)
sim>
````
#### Conclusion

The "Permission denied" I/O error should not be halting the simulation.  It should return a suitable hardware error to VMS indicating that the device is inaccessible.

It would be even better if an error were emitted at ATTACH time, indicating that the physical device can not be accessed without administrator rights.  Note, that this, too, should not prevent a running (or paused) OS from continuing, possibly to an orderly shutdown.

Halting the simulation of a running OS is the wrong response to a device error.  The OS can handle the error, and if the user doesn't like the response, (s)he can always do an orderly shutdown or manually halt the simulator.

The `Device OK - Type: CD_ROM, Number: 0
Removable Device
`  messages also seem superfluous.

**Comment by markpizz** [comment] 2018-02-24 19:12
> The simulator is run without admin privs (the OpenVPN tap config allows network access w/o rights). This will turn out to be the trigger for the error.

FYI 2 things:

1) Admin privileges are not necessary on Windows using basic WinPcap networking (or the newer npcap).  This is true as long as the npf service is started at OS boot time (which is the default).

2) OpenVPN tap is not necessary at all on any Windows version back to XP with the latest simh code.  The original network implementation got strange runt packets from WinPcap that it didn't know what to do with.  As it turns out, these runt packets were merely short packets (< the minimum ethernet frame size) emitted by activities of the host system.  They most usually were ARP packets.  The OpenVPN tap mechanism merely padded all small packets to the minimum frame size thus allowing the XQ layer to see all of the interesting traffic needed to support simulator<->host communication.  Once this fact was realized, along with the fact that pcap never captures physical runt packets from the wire, these short packets were padded to the minimum frame size and the need for something else to do that (OpenVPN tap) was eliminated.

Now to the points you raised:

> Conclusion
> The "Permission denied" I/O error should not be halting the simulation. It should return a suitable hardware error to VMS indicating that the device is inaccessible.

Well, maybe.  Essentially all other simulated devices end up with a simulator in an indeterminate state when an OS error is returned by a call to C run time functions, etc.  We just never see those so no one complains.  I'll look into whether there is a reasonable way to reflect errors at this late stage, but achieving that might cause major restructuring of things.

> It would be even better if an error were emitted at ATTACH time, indicating that the physical device can not be accessed without administrator rights. Note, that this, too, should not prevent a running (or paused) OS from continuing, possibly to an orderly shutdown.

This is a great suggestion.  Of course, it would be easy if media was present when the attach was performed.   Otherwise, determining whether the current process has sufficient privilege to perform some operation later might be hard.  Attach deliberately doesn't require media since it is reasonable for physical media to be inserted and removed from a CDROM drive during simulated system operation.   

> Halting the simulation of a running OS is the wrong response to a device error. The OS can handle the error, and if the user doesn't like the response, (s)he can always do an orderly shutdown or manually halt the simulator.

This is a completely true statement, but the code implementing many/most device simulators wasn't initially structured to convey error status back into the simulators since errors essentially never happen with simulated media.

> The Device OK - Type: CD_ROM, Number: 0 Removable Device messages also seem superfluous.

Agreed!

FYI:
After I implemented the CDROM support, I tried to use directly connected CDROM media a couple of times and found that the performance of walking the ODS2 file system data structures at CDROM seek speeds was so slow that it seemed that it was faster merely to rip the whole CDROM to an image file and use that instead.  
```
sim> ATTACH -C RQn CDROM-Image.vhd //./cdrom0
```
should work now to create a usable image.

**Comment by tlhackque** [comment] 2018-02-24 22:01
Last I knew, OpenVPN TAP was needed for multiple SimH instances (e.g. a SimH cluster on a notebook), and at one point, SimH to the emulation host networking to work.  But that may have changed; I've lost track.  Anyhow, that's how my machine is set up.

Additional information:

If the CD is present in the drive when SimH is started, the ATTACH reports an ODS2 Filesystem and the volume name as usual.  The permission error is only when the drive is empty when the init file runs.

I tried running SimH as administrator & the drive empty.  After booting VMS, I issue the mount, then insert the CD after the OPCOM OPRQST message.  I still get the `I/O error - permission denied`.  So this appears to be one of the "Windows error mapped to some handy POSIX errno" cases.  It would be nice to know what windows error, but I'm not setup to debug on the machine with a local CD drive.  Perhaps the file descriptor left open at attach is in a strange state when there's no media, and needs to be `clearerr()`'d or re-`open`ed later?

In any case, this should be easy for you to reproduce.

>  I'll look into whether there is a reasonable way to reflect errors at this late stage, but achieving that might cause major restructuring of things.

It should be setting an error bit (or two...) in the register - the devices all have them, and the OS drivers expect them.  Possibly adjusting the DMA address/WC to reflect the partial transfer for read/writes. `longjmp()` may be your friend.

> Of course, it would be easy if media was present when the attach was performed. Otherwise, determining whether the current process has sufficient privilege to perform some operation later might be hard. 

Understood - but it seems the first step to understand why "privilege error" is being returned from a "run as administrator" cmd window...

> Attach deliberately doesn't require media since it is reasonable for physical media to be inserted and removed from a CDROM drive during simulated system operation.

Agree.  But putting it in later shouldn't crash the emulation...

> Essentially all other simulated devices end up with a simulator in an indeterminate state when an OS error is returned by a call to C run time functions, etc.

"simulator in an indeterminate state" = wince, tears...

> the code implementing many/most device simulators wasn't initially structured to convey error status back into the simulators since errors essentially never happen with simulated media.

I always thought that a mistake.  Not checking for errors is one of the top causes of bugs in software at large - even `printf("hello world\n");` can fail.  It is something we're all guilty of, at one time or another.

And when raw access to physical devices is involved, it's a bigger issue, as shown here.  The usual simulated devices (most backed by disks) have all the host OS error recovery behind them; statistically, "essentially never happen" isn't a bad bet.  But with physical devices, you connect a 20 yr old SCSI disk, or a CDROM, or a cable insertion bounces, and real errors definitely will happen.


>FYI:
>After I implemented the CDROM support, I tried to use directly connected CDROM media a couple of times and found that the performance of walking the ODS2 file system data structures at CDROM seek speeds was so slow that it seemed that it was faster merely to rip the whole CDROM to an image file and use that instead.

Thanks for the suggestion.

I installed this VMS instance from a physical CDROM, and speed wasn't an issue.  Of course, install is backup/image from a contiguous saveset to a disk image - which isn't going to differ much from ATTACH -C.

I have literally hundreds of CDROMs to mount and inventory; rip to CD isn't feasible or useful.  

I expect it's a great idea for a CD that will be accessed many times - e.g. a doc disk used with bookreader.  

For installation, or  "mount, look, dismount & never again", I expect it would be slower, since the data is only looked at once.  For inventory, I only need to access the index file & a couple of text files.  Copying the rest of the CD is a waste.

**Comment by markpizz** [comment] 2018-02-25 01:39
Hmmm...  There are several ways to improve this:

1) If the operator (me) forgets to set the RQ device that is being attached as a RRD40 (or CDROM), then the attach (with media present) will succeed, but a mount operation will then cause a similar I/O problem when a write attempt is made to the media to mark the file system as mounted.  The innate read-only status of this device needs to be propagated back into the RQ device as equivalent to the unit being marked read only or a read-only attach having been performed (-R).
2) The problem you're seeing really isn't related privilege.  It is completely related to media insertion after the attach.  I'm surprised that I didn't see this problem previously.  There is useful/required information gathered as part of a successful attach with media present which hasn't happened in this circumstance.  I must have tested starting with media inserted, removed it, tested that failing case and then inserted media and things worked since the first attach I'd done properly initialized data in the UNIT structure.  
3) Remove the noise that is emitted about this being a CDROM

The sim_disk APIs return error status reflecting what the OS/driver has passed back.  the RQ device simulation (and others) is where the real problem handling errors needs to happen.  None of that is actually necessary here since these issues are all within sim_disk.c

Handling host system hardware errors in specific device simulations is left for another day.

The code I just fixed is all Windows specific.  Linux and OS X can also handle this stuff, but I need 
1) a way to determine that a particular file (by file name or open file descriptor) is connected to a CDROM device.  
2) an API/Ioctl to get the physical sector size of a particular file (by file name or open file descriptor).  
3) an API/Ioctl to eject a CDROM device

**Comment by markpizz** [comment] 2018-02-25 01:42
>Last I knew, OpenVPN TAP was needed for multiple SimH instances (e.g. a SimH cluster on a notebook), and at one point, SimH to the emulation host networking to work. 

That might be necessary/useful if the notebook computer didn't have any working LAN interfaces and thus wanted to run a cluster within the single notebook computer.  Otherwise, a single wired LAN interface can have an arbitrary set of cluster members either on the local LAN network and/or internal to that same host system with all of the internal simulators attaching to the Wired LAN network interface.

**Comment by markpizz** [comment] 2018-02-25 04:52
Updated windows binaries are available including fix for the problem you were experiencing.

**Comment by tlhackque** [comment] 2018-02-25 14:26
Thanks, I'll give the updated binaries a whirl.

On the other items:

On an airplane (and in many cars :-), there are usually no LAN interfaces that are up... I'll stick with my legacy configuration.

>If the operator (me) forgets to set the RQ device that is being attached as a RRD40 (or CDROM),...
> The innate read-only status of this device needs to be propagated  ...

In the generic case, the status of the device actually depends on both the device and the medium that's inserted.  A CD R/W drive is writable if the medium is, and isn't if the medium is not.  The RRD40 emulated device is read-only, but CD writers were attached to VMS machines.  So the ultimate call has to be made at the RQ level, not in sim_disk.  The same applies to DVDs.

Thus, media insertion/removal need to update the device attributes.  The device class and capabilities can be determined at ATTACH time (it's a DVD/CD drive capable of eject).  The status (RO/sector size) depend on the medium and are dynamic.

For the other hosts (I assume you know about VMS :-): I can't speak to OSX, but for Linux:

 >a way to determine that a particular file (by file name or open file descriptor) is connected to a CDROM device.

`/dev/cdrom` and `/dev/dvd` link to "the" drive (not sure what happens if you have more than one; I suspect it takes the first one it sees.)  `/media/cdrom0` (1,2,3,...) are the conventional mount points; they don't apply to raw access.

I don't know of a generic answer (e.g. for multiple drives that use more than one driver).  For the common case (one drive, or all drives use the same driver), you can `(f)stat()`, then look at `major(st_mode)` & `minor(st_mode)` on that device, and the one you aren't sure about.  These will match if you're pointing at **the** CD/DVD reader.   In any case, the `major()` of `/dev/cdrom` will be the same for all CD/DVD drives that use the same driver.  The value may vary due to dynamic allocation, as well as the specific manufacturer/model and/or interface type.    `minor()` will give the instance (drive) number.  

`$GETDVI_W`'s more sensible device class and attributes abstractions would be nice...

There is more detailed data in `/sys/dev/block` (or `/sys/dev/char`), but again, on a R/W drive, you can't tell if it's read-only until you know what medium is inserted.  You probably want the `ioctl()`s.

For a lazy approach, `/proc` is available on all the distributions that I use.

````
 cat /proc/sys/dev/cdrom/info
CD-ROM information, Id: cdrom.c 3.20 2003/12/17

drive name:             sr0
drive speed:            48
drive # of slots:       1
Can close tray:         1
Can open tray:          1
Can lock tray:          1
Can change speed:       1
Can select disk:        0
Can read multisession:  1
Can read MCN:           1
Reports media changed:  1
Can play audio:         1
Can write CD-R:         1
Can write CD-RW:        1
Can read DVD:           1
Can write DVD-R:        0
Can write DVD-RAM:      0
Can read MRW:           1
Can write MRW:          1
Can write RAM:          1
````
>an API/Ioctl to get the physical sector size of a particular file (by file name or open file descriptor).

For CDs, mode 1 is always 2048 bytes, mode 2 2236.  Mode 2 has no ECC, and sensible computers won't use it (except for video disks).  In any case, this is an attribute of the media, not the drive.

See `ioctl()` BLKSSZGET (logical) and BLKBSZGET (physical) in `linux/fs.h`.  But you actually need something like this:
````
#ifdef BLKSSZGET
int blkdev_get_sector_size(int fd, int *sector_size)
{
    if (ioctl(fd, BLKSSZGET, sector_size) >= 0)
        return 0;
    *sector_size = DEFAULT_SECTOR_SIZE;
    return -1;
}
#else
int blkdev_get_sector_size(int fd __attribute__((__unused__)), int *sector_size)
{
    *sector_size = DEFAULT_SECTOR_SIZE;
    return 0;
}
#endif
````

>an API/Ioctl to eject a CDROM device

From: https://www.kernel.org/doc/Documentation/ioctl/cdrom.txt - CDROMEJECT and CDROMCLOSETRAY are probably of interest.  And CDROM_MEDIA_CHANGED, CDROM_DRIVE_STATUS


Do you want to create a separate issue for handling C RTL error returns properly?  (Especially those that should reflect hardware errors to simulated devices.)  It shouldn't be lost...

**Comment by tlhackque** [comment] 2018-02-26 00:11
First media insert after attach on Windows confirmed to work with 70d8f759.

Thanks for the quick fix.

**Comment by markpizz** [comment] 2018-02-26 15:30
> > If the operator (me) forgets to set the RQ device that is being attached as a RRD40 (or CDROM),...
The innate read-only status of this device needs to be propagated ...
> 
> In the generic case, the status of the device actually depends on both the device and the medium that's inserted. A CD R/W drive is writable if the medium is, and isn't if the medium is not. The RRD40 emulated device is read-only, but CD writers were attached to VMS machines. So the ultimate call has to be made at the RQ level, not in sim_disk. The same applies to DVDs.

Supporting writable CD/DVD activities requires a whole additional set of operations beyond the basic write behavior that a normal disk needs.  sim_disk doesn't support those now since there are no devices that actually need this functionality.  CD writers on VMS machines may have existed but they weren't connected behind RQ or RP device controllers.  If/when we need more functionality here (possibly to support SCSI passthrough) we'll revisit this subject, but I'd expect that  we'll probably leave writing optical media up to external programs on the host systems.

---
Thanks for the Linux CD I/O details you provided.   Direct CD access is not a high use activity since its been there for many years and you usage was the first to encounter the problem.

---

> Do you want to create a separate issue for handling C RTL error returns properly? (Especially those that should reflect hardware errors to simulated devices.) It shouldn't be lost...

This is a big can of worms.  Attempting to pass physical errors through the simulation doesn't seem to make sense.  I say this since, once an error is passed through the simulator's driver will attempt any number of error recovery/retry activities at arms length (including bad block replacement) which we explicitly don't have support for.  Media with errors needs to be gingerly handled on the host system or a specific host system designed to extract and/or recover data.  Beyond these considerations, I don't see a reasonable way to test these failure modes either.

After saying this, I looked in the RQ simulation code and I see that it makes an attempt to pass data transfer error indications through to the simulator.  The failure that started this issue was due to various necessary details not having been gathered at ATTACH time since no media was present.  The current code now effectively reopens the device when media comes online, so the necessary information is then gathered.

Many other device simulations have a pseudo register usually named STOP_IOE which, if set, causes simulation to stop on an error, but the only error they usually handle is the device not attached which isn't a C RTL error.  Several of these are 'buffered' disks which means that the entire disk's contents are held in a buffer in the simulator, so C RTL errors outside of attach and detach can't actually happen.  An example that isn't buffered is the RK device.  A C RTL read or write error stops simulation unconditionally.  The user might attempt to continue from that state, but all bets are off regarding whether anything useful can happen.

So, in the end, simulators need to work with good data.  Host system hardware errors need to addressed on the host, not through simulators.

**Comment by tlhackque** [comment] 2018-02-27 04:39
Yes, it's a can of worms.  It can probably be reduced to a smaller can if we consider the read-only device case.  That inhibits bad block replacement, etc.  Removable media (CD, floppy) are probably the most interesting since there are more opportunities for users to do the unexpected.

And, yes, I do tend to find bugs.  This is the first time I've tried using a physical device with SimH, so it didn't take **me** long :-)

**I found another instance of an I/O error halting the simulation.** (With yesterday's code)

I added to the configuration shown above:
```
set rq2 enable
set rq2 rrd40
attach rq2 -e filename.iso ;  This ISO from the the CD in the physical drive.
```
I again started simh with no CD in the drive.
````
RQ1: unit is read only
RQ2 (found the ODS2 volume)

... boot, login

mount/over=id dua2:      ; .iso - it's happy.  ana/disk, take directories

mount/over-id dua1: 

RQ I/O errorr: Unknown error
RQ1 RQ I/O error: Unknown error
vms.ini-29> b cpu
I/O error, PC: .........
````

This is reproducible without touching dua2.

The trick seems to be this:

1) setup the mount command in the console (telnet in my case) window.  **Don't type &lt;CR&gt;**

2) Close the CDROM drawer.  Windows will spin up the drive to see if it recognizes the file system.

3) **While it is spinning for windows**, hit &lt;CR&gt;.

**The simulation crashes as above.**

It would be nice if the error messages called a simh strerror that includes the OS error string as well as the POSIX error.  Especially when the POSIX.CRTL error is "Unknown error".  I don't know how often GetLastError is valid after these, but it wouldn't hurt to try to report it.  E.g. if non-zero " - Last windows error: ..."

FWIW, I encountered some possibly similar issues in a CDROM reader/ISO writer that I wrote today.

What I found was that the `DeviceIoControl IOCTL_DISK_GET_DRIVE_GEOMETRY` could fail with three (so far) interesting error codes:

- `ERROR_NOT_READY` or `ERROR_NO_MEDIA_IN_DRIVE` - Seems to be a timeout of several seconds while the ioctl tries to spin up the drive.
- `ERROR_MEDIA_CHANGED` - this one goes away if you retry the `DeviceIoControl`.  It shows up more or less when you expect - oddly, even if you do the ioctls to eject & load media.

(This is Perl code using the `WIN32API::File` module; it's pretty much a direct map to the C Windows API.)

**Comment by markpizz** [comment] 2018-02-27 21:52
Hmmm.. I don't see the failure you are seeing.  I'm traveling and the DVD drive I'm using is USB connected to my laptop.  Prior to the drive door being closed, the device appears cleanly to VMS as offline with a mount command.  The instant the drive door is closed, the mount command pauses until the media is spun up and then the mount succeeds.  This might behave differently with a different (SATA ) connected DVD drive.  I'll be back to my desktop over the weekend and I should be able to try with the SATA DVD drive then.

Meanwhile, I've revised the error reporting to attempt to display the error text related to GetLastError() in this case.  This 'might' report something useful, and it might not.  There is significant distance between when the system call fails (thus setting the last error), and when the error message is printed.  Some other system call might have been executed which would then overwrite the last error information.  A new set of Windows Binaries should be available in a few minutes.

**Comment by markpizz** [comment] 2018-04-08 05:58
Along the way to fixing this, I enriched the error message generation which now produces:
```
$ moun/over=id dua2
RQ I/O error: Permission denied
RQ2 RQ I/O error: The data area passed to a system call is too small.

I/O error, PC: 80DA96E5 (BBS R1,@#80004EC0,80DA96DF)
sim>
```
This is certainly much more useful information.  Thanks for the suggestion.

----
Part of the best solution for this is for sim_disk to extend the auto format detection that sim_disk uses when attaching files/devices.  Previously, attempts to open any file (without explicitly specifying the format at attach time), the file was attempted to be opened as a VHD, and if that failed if fell back to the standard SIMH format (which uses the C RTL fopen).  The Windows C RTL will successfully open a file named //./CDROM0 (or \\.\CDROM0), but I/O to the file will end up getting the above error if the data being read isn't a multiple of 2K on a 2K address boundary.  Determining that this open file is really a CDROM isn't really possible, so files like this really need to be opened using RAW access mode.  So, sim_disk_attach's auto format detection now will try a RAW open before falling back to the SIMH (fopen) approach.  This has the side effect of essentially making RAW the default access since essentially all normal files can be opened in RAW mode (accessed with open,read,write,close rather than fopen,fread,fwrite,fclose).  I don't think there is a real down side to that change, but significantly different code paths will be used hence forth when accessing disks on all disk device simulations which use sim_disk.

Please confirm that this works correctly now.

**Comment by markpizz** [comment] 2019-05-02 16:17
> I found another instance of an I/O error halting the simulation. (With yesterday's code)
>
> I added to the configuration shown above:
> 
```
set rq2 enable
set rq2 rrd40
attach rq2 -e filename.iso ;  This ISO from the the CD in the physical drive.
```
> I again started simh with no CD in the drive.
```
RQ1: unit is read only
RQ2 (found the ODS2 volume)

... boot, login

mount/over=id dua2:      ; .iso - it's happy.  ana/disk, take directories

mount/over-id dua1: 

RQ I/O errorr: Unknown error
RQ1 RQ I/O error: Unknown error
vms.ini-29> b cpu
I/O error, PC: .........

```

The failure while mounting DUA1 (attached to the ISO image) was the one dangling problem in this issue that I was unable to reproduce.

As it turns out, it is data dependent and related to the earlier change that gave priority to RAW vs SIMH format during the attach.

It was reported again specifically in #696 and is now fixed.

The problem relates to the file system structure in the attached ISO file.  VMS's mount will be looking for a file system data structures and, while doing that might attempt to access an area of the file which is beyond the size of the ISO container, but within the logical size of the expected media space.  When SIMH format is used, the disk access does a fseek() followed by a fread() which returns no data, but also no error.  The RAW mode logically did the same seek, but it the read operation returned EOF which wasn't handled as a special no-error->expected case.  That has now been fixed.

**Closed by markpizz** 2019-05-02 16:17 UTC
Labels: Bug
