### ISSUE TITLE
Printing from wps-8

### ISSUE THREAD

**Issue by RaymiiOrg** [simh/simh#353] opened 2016-11-23 19:27 UTC
I'm using simh 3.9 (or 4 beta) and it seems that printing from WPS-8 (PDP-8) fails. Here's my INI file:

    set cpu 32K
    set cpu  noidle
    set tto 7b
    attach rx0 wps78v3.4.rx01
    attach rx1 wps-doc.rx01
    set LPT enable
    attach LPT printer.txt
    boot rx0
    exit

I can create documents and send them to the printer, but they hang. The printing gives an error, as seen on the below screenshots.

The printer.txt file also stays empty, a 0 byte filesize.

Selecting different destinations from wps-8 doesn't help.

How can i get my documents to be sent to the host system from wps-8?

![xterm_2016-11-23-005](https://cloud.githubusercontent.com/assets/1927494/20575820/436d4ff0-b1bb-11e6-9bb8-c2dabe7237d1.png)
![xterm_2016-11-23-004](https://cloud.githubusercontent.com/assets/1927494/20575824/43704bd8-b1bb-11e6-8258-3d4fad534caf.png)
![xterm_2016-11-23-003](https://cloud.githubusercontent.com/assets/1927494/20575821/436f0e4e-b1bb-11e6-8f82-5bcc838bbc0f.png)
![xterm_2016-11-23-002](https://cloud.githubusercontent.com/assets/1927494/20575822/436f5e4e-b1bb-11e6-93b1-919c9f28703b.png)
![xterm_2016-11-23-001](https://cloud.githubusercontent.com/assets/1927494/20575823/436fbd58-b1bb-11e6-86a5-1139f860afb9.png)

**Comment by markpizz** [comment] 2016-11-23 19:49
Hi @RaymiiOrg, thanks for using the github issue system to report this problem.  Would you mind adding your full name to your GitHub profile so folks who read this know who you are (no email is necessary).  Thanks.

Meanwhile as to the issue at hand, someone can fix this if they can reproduce it.  The person fixing it may nor may not have any PDP8 experience and may or may not have any wps-8 experience, so can you please provide enough information so that the problem can be reproduced?  This might include the disk images you mention in your configuration file, and precise input steps to get to the point where the problem occurs.

Thanks.

- Mark

**Comment by RaymiiOrg** [comment] 2016-11-24 04:51
Hi Mark,

The disk image is from here: http://www.pdp8.net/images.shtml - this one: https://www.pdp8online.com/ftp/images/wps/wps78v3.4.rx01 and this is rx1, a document storage drive: https://www.pdp8online.com/ftp/images/wps/wps-8-doc.rx01. Since it's quite vt52 dependent, you need to use xterm in vt52 mode specifically: https://groups.google.com/d/msg/pidp-8/o1cHg93t4uM/7yeD41bCCAAJ. 

The system starts up, you enter the date and then get in the main menu. Choose option C to create a document, type some test text and return to the menu using the (P)F1+M key twice.

Choose option P for printing and press return for the last used document. Type YES to confirm printing.

The expectation is that the lpt printer text file defined in the simh-ini file is filled with the document in some form or another. The actual result is an error in the system as shown on the screenshots and the attached printer text file stays empty.

**Comment by archivisth** [comment] 2016-12-07 18:22
All the PDP8(E/A) printer controllers are compatible - the LP8E, the LA8, the LE8, etc - and WPS-8 claims to support at least some of them.

For me to debug this, I need a Telnet client with VT52 support that runs on Windows. Suggestions?

**Comment by RaymiiOrg** [comment] 2016-12-07 18:28
In the initial mailinglist thread there was a screenshot of HyperTerm which looked OK. Otherwise KEA or SecureCRT?

**Comment by dgesswein** [comment] 2016-12-16 02:39
WPS supports 3 printers
LPQ - Didn't fully verify but likely the VT78 device code 50 whose IOT's are significantly different than what SIMH currently supports.
DP - Device code 66 which is the device code that SIMH supports for LPT. It requires 6660 to set the printer flag which SIMH doesn't implement. The VT78 port have other changes to the IOT's that don't seem to be required.
DP2 - Device code 3x for the serial interfaces. Didn't investigate since SIMH doesn't support it.

Adding to pdp8_lp.c
    case 0:
        dev_done = dev_done | INT_LPT;                 /* set flag */
        int_req = INT_UPDATE;                          /* update interrupts */
        return AC;

to pdp8_lp.c and selecting DP printer makes it work.

The question now is what is the desired solution to the problem.

1) Add the code. This makes the LPT device probably not match any real PDP-8 device. Quickly solves this issue.
2) Add some mode setting option to LPT device to select current LC8E? emulation, VT78 device 66 emulation, and possibly others. I could use suggestion on how this should fit in with SIMH. Not sure how many interfaces I can find documentation on. 8/E had 5 different printer boards, VT78 has the three printer interfaces and haven't looked at other 8's. There are things like the character positioning, status and data readback that some of the devices support that doesn't seem practical to fully support.
3) Support multiple LPT devices. All the PDP-8's support multiple LPT devices. For non CMOS 8's the device code is user settable. Don't know how to do this in SIMH and if there is interest in doing so.

VT78 ports documented in users and programmers guide in
http://www.mirrorservice.org/sites/www.bitsavers.org/pdf/dec/pdp8/cmos8/
LC8E is in maintenance manual volume 3 in
http://www.mirrorservice.org/sites/www.bitsavers.org/pdf/dec/pdp8/pdp8e/

**Comment by archivisth** [comment] 2016-12-16 03:17
Actually, the LS8-E added the decoding of IOT 0; it's in the schematics and the documentation that accompanies it. So I'd be in favor of simply adding the line of code. It won't break anything else.

In theory, the PDP-8 simulator should be "modeled", like the PDP-11, but it's quite a PITA to do, and I'm not sure about the ROI. So far, all the software seems to be tolerant of the "simulator as superset" idea. If a contrary case surfaces - that is, a program that relies on the intimate details of a Straight 8 vs an 8/I, or an 8/I vs an 8/E - other than diagnostics, I'd revisit the issue.

**Comment by markpizz** [comment] 2016-12-16 18:06
Remy,

Please confirm that the latest code fixes the problem you were seeing, and if so close this issue.

Thanks.

**Comment by RaymiiOrg** [comment] 2016-12-18 08:08
After changing the printer type to DP (Print menu, `DD DP`), it seems to work, see attached screenshots.

At first I thought it did not work, because the text file defined in simh.ini is only updated with the text once I close the simh window. After printing and not closing, it stays empty. After I closed the simh window, there were about 20 prints in the text file.

Would it be possible to explain why that happens?

Huge thanks for taking the time and effort to make it work!

![wps8term_2016-12-18-008](https://cloud.githubusercontent.com/assets/1927494/21292317/2b6cb9aa-c501-11e6-85f8-fa48b87290b6.png)
![selection_2016-12-18-007](https://cloud.githubusercontent.com/assets/1927494/21292316/2b6ca9c4-c501-11e6-9b66-88b06014f96a.png)
![wps8term_2016-12-18-006](https://cloud.githubusercontent.com/assets/1927494/21292315/2b6b9106-c501-11e6-932a-ac112b2b6eae.png)
![wps8term_2016-12-18-005](https://cloud.githubusercontent.com/assets/1927494/21292318/2b6da720-c501-11e6-82ac-caabfb724411.png)

**Comment by dgesswein** [comment] 2016-12-18 17:11
On Sun, Dec 18, 2016 at 12:08:47AM -0800, Remy wrote:
> 
> Would it be possible to explain why that happens?
> 
It is likely the buffering on the writes by C library/OS. For small writes
like your test print the contents get stuck in the buffer until the file is
closed. You can flush without exiting SIMH by detaching the device or
attaching to another file. I haven't seen a command to flush the open file.

**Comment by RaymiiOrg** [comment] 2016-12-18 20:03
Thanks for the explanation! Printing now works, so I think this issue can be closed?

**Comment by markpizz** [comment] 2016-12-18 20:05
The C runtime's FILE* is automatically flushed whenever you return to 
the sim> prompt.

You should then be able to view the contents of the file with more/cat/less 
or some editor.

If return to the simulation from that point, and print more to the same printer 
device subsequent data will be written beyond the data you previously wrote.

If you'd like to start writing in a new file, detaching and a subsequent attach 
to a different file are indeed the right steps.

**Closed by markpizz** 2016-12-18 20:05 UTC
