### ISSUE TITLE
simh tmxr: segfault when remote end is fast telnet

### ISSUE THREAD

**Issue by b4** [simh/simh#423] opened 2017-03-21 16:19 UTC
- #### Context

When attempting to send data back/forth through the "virtual serial link" between simulations when the remote end is not simh but is instead a telnet server SIMH segfaults.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 4
    Host Platform:
        Compiler: GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)
        Simulator Compiled as C arch: ARM (Release Build) on Mar 21 2017 at 13:06:19
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 4ms
        OS: FreeBSD verdigris 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 11:13:27 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/arm.armv6/usr/src/sys/IMX6  arm
        git commit id: b2cd329f
```
- #### how you built the simulator or that you're using prebuilt binaries

```
*** Warning *** Using local cc since gcc isn't available locally.
*** Warning *** You may need to install gcc to build working simulators.
lib paths are: /lib /usr/lib /usr/lib/compat /usr/local/lib /usr/local/lib/perl5/5.24/mach/CORE /usr/local/llvm37/lib
include paths are: /usr/include /usr/local/include
using libm: /usr/lib/libm.so
using librt: /usr/lib/librt.so
using libpthread: /usr/lib/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/local/lib/libpcreposix.so /usr/local/include/pcreposix.h
using libdl: /usr/include/dlfcn.h
using mman: /usr/include/sys/mman.h
using libpcap: /usr/include/pcap.h
using libvdeplug: /usr/local/lib/libvdeplug.so /usr/local/include/libvdeplug.h
***
*** vax780 Simulator being built with:
*** - compiler optimizations and no debugging support. FreeBSD clang version 3.8.0.
*** - dynamic networking support using FreeBSD provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP NAT(SLiRP)
***
*** git commit id is b2cd329f4c02a80d10ef5906835917c9babcd31f.
***
cc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow  -DSIM_GIT_COMMIT_ID=b2cd329f4c02a80d10ef5906835917c9babcd31f -DSIM_COMPILER="FreeBSD clang version 3.8.0" -I . -D_GNU_SOURCE -I/usr/local/include -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_GLOB -DHAVE_SHM_OPEN  sim_BuildROMs.c -o BIN/BuildROMs
BIN/BuildROMs
rm -f BIN/BuildROMs
cc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow  -DSIM_GIT_COMMIT_ID=b2cd329f4c02a80d10ef5906835917c9babcd31f -DSIM_COMPILER="FreeBSD clang version 3.8.0" -I . -D_GNU_SOURCE -I/usr/local/include -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCREPOSIX_H -DHAVE_DLOPEN=so -DHAVE_GLOB -DHAVE_SHM_OPEN  VAX/vax_cpu.c VAX/vax_cpu1.c VAX/vax_fpa.c VAX/vax_cis.c VAX/vax_octa.c  VAX/vax_cmode.c VAX/vax_mmu.c VAX/vax_sys.c  VAX/vax_syscm.c VAX/vax780_stddev.c VAX/vax780_sbi.c VAX/vax780_mem.c VAX/vax780_uba.c VAX/vax7x0_mba.c VAX/vax780_fload.c VAX/vax780_syslist.c PDP11/pdp11_rl.c PDP11/pdp11_rq.c PDP11/pdp11_ts.c PDP11/pdp11_dz.c PDP11/pdp11_lp.c PDP11/pdp11_tq.c PDP11/pdp11_xu.c PDP11/pdp11_ry.c PDP11/pdp11_cr.c PDP11/pdp11_rp.c PDP11/pdp11_tu.c PDP11/pdp11_hk.c PDP11/pdp11_vh.c PDP11/pdp11_dmc.c PDP11/pdp11_dup.c PDP11/pdp11_td.c PDP11/pdp11_tc.c PDP11/pdp11_rk.c PDP11/pdp11_io_lib.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -DVM_VAX -DVAX_780 -DUSE_INT64 -DUSE_ADDR64 -I VAX -I PDP11 -DHAVE_PCAP_NETWORK -I/usr/include/ -DBPF_CONST_STRING -DUSE_SHARED -DHAVE_VDE_NETWORK -DHAVE_TAP_NETWORK -DHAVE_BSDTUNTAP -Islirp -Islirp_glue -Islirp_glue/qemu -DHAVE_SLIRP_NETWORK -DUSE_SIMH_SLIRP_DEBUG slirp/*.c slirp_glue/*.c -o BIN/vax780 -L/lib -L/usr/lib -L/usr/lib/compat -L/usr/local/lib -L/usr/local/lib/perl5/5.24/mach/CORE -L/usr/local/llvm37/lib -lm -lrt -lpthread -lpcreposix -L/usr/local/lib/ -lvdeplug -Wl,-R,/usr/local/lib/ -L/usr/local/lib/
```
- #### the simulator configuration file (or commands) which were used when the problem occurred.

```
set cpu 64m
set cpu idle=4.3bsd
at rq0 ucbvax-ra92-root.dsk
set rl dis
set rq1 dis
set rq2 dis
set rq3 dis
set hk dis
set ts dis
set tu dis
set lpt dis
set rp dis
set dz en
set dz lines=8
set dz 8b
set dz lines=8
set dz 8b
attach dz -a -m line=0,Connect=127.0.0.1:6000,SPEED=9600
attach dz -a -m line=1,5001;notelnet
attach dz -a -m 5000
set ry dis
set vh en
set vh0 dhu
set vh0 modem
;set debug -T stdout
;set VH DEBUG=REG
set xu en
att xu vde:/tmp/vde
load -o boot42 0
dep r10 9
dep r11 0
set tti 7b
set tto 7b
attach TODR TOY_CLOCK
#run 2
```
- #### the expected behavior and the actual behavior

Expected: Not to segfault.
Actual: segfaulted on data receive.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

```
#0  $a.51 () at sim_tmxr.c:1967
        tmp = 24 '\030'
        i = 0
        nbytes = 3
        j = 0
        lp = (TMLN *) 0x215ea000
#1  0x000e3e30 in $a.51 () at sim_tmxr.c:1851
        tmp = 24 '\030'
        i = 0
        nbytes = 3
        j = 0
        lp = (TMLN *) 0x215ea000
```
GDB's ideas as to what happened are above.

**Comment by markpizz** [comment] 2017-03-23 15:15
Hi Cory,

I'm traveling for the next couple of weeks.

In any case, I'm looking at this now and it would be simplest if I could get enough info to reproduce the problem.  

Given the GDB info you've provided it seems to definitely be related to activities on Line=0 since i=0.  It would be useful to know what *lp looked like (i.e. all the members of the structure), in particular what lp->telnet_sent_opts is as well as the 256 bytes that pointer points at.  simh DZ device Debug info would also be useful, but without knowing more about when the crash happens (i.e. how long the simulator runs before it crashes), I yet can't suggest what to record.  Debug data written to a file might be incomplete when a SEGFAULT happens, and the most interesting info will be the last few lines of debug info.

- Mark

**Comment by markpizz** [comment] 2017-05-30 06:24
Cory,

Is there some way you can suggest that I could reproduce this problem?

Apart from reproducing it, can you capture (with WireShark) the whole TCP session that ends causing the segfault?  If so, can you zip the captured file and drop it here.

Thanks,

- Mark

**Comment by b4** [comment] 2017-05-30 06:24
Sure - but likely not for about a week. Work has me busy.

**Comment by markpizz** [comment] 2017-05-30 06:26
No problem.  It took me 2 months to get back to this.

**Comment by markpizz** [comment] 2017-06-21 22:13
Cory,

Ping...  

I really don't like latent segfaults...  Data to track down the problem is needed.

Thanks.

- Mark

**Comment by b4** [comment] 2017-06-21 22:14
Sorry - have been busy with a job move and in-progress apartment move. 

I am setting myself a reminder to get you more info this weekend.

**Comment by markpizz** [comment] 2017-11-15 02:56
pinging again 5 months later...  :-)

**Comment by markpizz** [comment] 2017-12-22 11:23
I think I just fixed this.  There was a problem if a telnet session sent telnet options just prior to closing the TCP socket  If the socket got closed, the response to the option requests gets dropped (not a problem), but we need to recognize that the line with the newly dropped TCP connection is no longer valid and stop referencing fields in the structure.

If you still reproduce this problem, please reopen this issue.

**Closed by markpizz** 2017-12-22 11:23 UTC
