### ISSUE TITLE
Losing Time In SIMH On VAX-11/780

### ISSUE THREAD

**Issue by porcupixel** [simh/simh#390] opened 2017-01-31 05:15 UTC
I've noticed that, both when running ITS in an emulated PDP-10 as well as UNIX/32V in a VAX 780 on my GNU/Linux machine, the time in the emulator slowly drifts out of sync with real time. The emulator and host machine are sitting mostly idle. I thought perhaps the host machine wasn't powerful enough (a 2.5GHz Intel Core 2 Quad) so I moved everything over to an even faster 12-core Opteron but it seems to have made no difference. I no longer have ITS set up on a PDP-10, so I don't have info on report about that but when running UNIX/32V in the VAX-11/780 I tried adding set cpu idle=32V just to see if it would make a difference and set the time & date correctly before going to bed. After getting up in the morning I found that this seems to have made no difference - It's off by about 11 minutes, so drifting be a little over a minute each hour.

I should also add that I've noticed this loss of time both when running the version of simh provided by my distro and when running from git master (git commit id: d14243c8.)

Based on a suggestion from Mark Pizzolato on the mailing list I stopped the simulator while booted with ^E and at the sim> prompt I entered the SHOW CLOCK command. I examined 'Ticks' vs 'Ticks Acked' and found them to be identical: 2,432,774. The output is replicated in full below.

I am submitting this as he suggested so as to dig deeper into what may be going on.

I am also include a copy of the config in case it is helpful: [dboot.txt](https://github.com/simh/simh/files/741136/dboot.txt)

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
> VAX 11/780 simulator V4.0-0 Beta        git commit id: d14243c8
> sim> show version
> VAX 11/780 simulator V4.0-0 Beta
> 	Simulator Framework Capabilities:
> 		64b data
> 		64b addresses
> 		Ethernet Packet transports:PCAP:TAP:NAT:UDP
> 		Idle/Throttling support is available
> 		Virtual Hard Disk (VHD) support
> 		RAW disk and CD/DVD ROM support
> 		Asynchronous I/O support
> 		Asynchronous Clock support
> 		FrontPanel API Version 3
> 	Host Platform:
> 		Compiler: GCC 4.8.4
> 		Simulator Compiled as C arch: x64 (Release Build) on Jan 29 2017 at 18:09:23
> 		Memory Access: Little Endian
> 		Memory Pointer Size: 64 bits
> 		Large File (>2GB) support
> 		SDL Video support: No Video Support
> 		PCRE RegEx support for EXPECT commands
> 		OS clock resolution: 1ms
> 		Time taken by msleep(1): 1ms
> 		OS: Linux pc 3.13.0-106-generic #153+7.0trisquel2 SMP Wed Dec 21 00:18:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
>         git commit id: d14243c8

- #### how you built the simulator or that you're using prebuilt binaries
This should include the output produced by while building the simulator
I compiled it with make vax780. The output produced while building the simulator is here: 
[compile.txt](https://github.com/simh/simh/files/741142/compile.txt)

- #### the simulator configuration file (or commands) which were used when the problem occurred.
[dboot.txt](https://github.com/simh/simh/files/741136/dboot.txt)

- #### the expected behavior and the actual behavior
The expected behavior is to maintain accurate time compared to a wall clock.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem
Install tapes and information about how to set up 32V in SIMH can be found at http://gunkies.org/wiki/Installing_32v_on_SIMH

**Comment by porcupixel** [comment] 2017-01-31 05:17
Oh, I forgot to include the output that I said I would:

> Simulation stopped, PC: 80000798 (BLBC 8000B6FC,80000798)
> sim> SHOW CLOCK
> Minimum Host Sleep Time:       1 ms (1000Hz)
> Host Clock Resolution:         1 ms
> Execution Rate:                27,597,545 instructions/sec
> Idling:                        Enabled
> Time before Idling starts:     20 seconds
> Calibrated Timer:              TMR
> Calibration:                   Always
> 
> VAX 11/780 clock device is TMR
> Calibrated Timer 0:
>   Running at:                59 Hz
>   Tick Size:                 16.949 msecs
>   Ticks in current second:   28
>   Seconds Running:           41,233 (11:27:13 hours)
>   Calibration Opportunities: 41,233
>   Instruction Time:          1132070421829
>   Real Time:                 4073318537
>   Virtual Time:              4073318527
>   Next Interval:             990
>   Base Tick Delay:           472,480
>   Initial Insts Per Tick:    5,000
>   Current Insts Per Tick:    467,755
>   Initializations:           4
>   Ticks:                     2,432,774
>   Ticks Acked:               2,432,774
>   Total Ticks Acked:         2,432,775
>   Tick Time:                 11:27:13.457627 hours
>   Initialize Base Time:      09:03:22.647
>   Tick Start Time:           09:03:22.647
>   Wall Clock Time Now:       20:30:50.229
>   Total Time Idled:          11:19:44.653 hours

**Comment by markpizz** [comment] 2017-01-31 05:28
Info here actually seems to correlate with your observed clock drift.   Notice that the simh timing facility seems to believe that the tick rate is 59Hz, while I suspect the UNIX time keeping is presuming a 60Hz tick rate.  That works out to be 1 tick per second, 60 ticks per minute and 3600 ticks per hour, or 1 minute per hour.

I'll look at the timing stuff to see if this is a rounding error.  Meanwhile you may want to config a kernel with a 50Hz tick rate and see how that tracks wall time.

**Comment by WILLIAMCORCORAN** [comment] 2017-01-31 07:08
Hello Porcupixel,

Seeing a similar drift between a simulated PDP-10 and a simulated VAX 11/780 on the same host is interesting.  

I noticed my clock would drift with 32V (SIMH/VAX 780) hosted on Apple's OS X whenever the OS would  go to sleep.  In general, sleeping is a OS specific function with often unusual side effects.

For example, simply closing the lid on my MacBook Pro would cause the host to sleep after a few moments.  SIMH was not too keen with sleep mode.  I would not expect SIMH to tolerate host sleeping in EVERY case due to the myriad of ways that host sleeping can be implemented on various hardware.    

Now, I don't know anything about your Linux box's hardware, but many systems today have some kind of sleep mode that is integrated with hardware.  So, you may want to disable it. 

I remember on an NCR minitower UNIX box, (early 1980s) the OS would dump the contents of memory into the dump device during power down.   If you hit the power switch, the system would turn the hardware off after dumping memory and saving key registers.  Then, once power was restored via the power switch, the system would reload its memory from the dump device, restore the appropriate registers, and jump to the proper subroutine and suddenly your UNIX box is brilliantly running with all processes in the same state as before the shutdown.  However, I remember the horror stories from the uninitiated that attempted to power down because the system had a few runaway processes---those buggers would still be there after powering back on.  Of course, performing the proper reboot operation saved the day.

My point being that should your host go to sleep, (possibly unbeknownst to you)  this could explain your simulated clock drift.  I can tell you for sure that my Apple OS X system went to sleep constantly and this caused problems with my SIMH 32V clock.   Also, while you try to figure this out, you may want to consider disabling throttle/idle.

Since at least the 1980s, UNIX vendors toyed around with sleeping hardware.   Well, today's systems universally implement sleep mode to appease the environmental power saving standards.  

I just wanted to share my experiences with SIMH and VAX 780 running UNIX 32V.   


Truly,

Bill Corcoran

**Comment by porcupixel** [comment] 2017-01-31 18:33
Thanks Bill. Neither of these machines ever go in any sort of sleep or power save mode. They're left running 24/7. The drift can be observed fairly quickly - Set the date & time correctly, hang out at the computer for a few minutes and you'll see it's already drifted a few seconds even though the computer did not enter any power saving mode (because they're both configured to never do so.)

**Comment by markpizz** [comment] 2017-01-31 19:13
@porcupixel As I mentioned previously, please try to build a kernel with 50Hz ticks and confirm one way or another about how well time in the OS tracks relative to the wall clock time.  Report results here.

Meanwhile, I don't have a test configuration with this OS available, so please change line 731 in sim_timer.c from:
```clk_tps = 1000000 / usecs;```
to:
```clk_tps = 1000000 / (usecs - 1);```

And test the system's timekeeping with BOTH the 60Hz kernel AND the 50Hz kernels and report back here about your results.

Thanks.

**Comment by porcupixel** [comment] 2017-01-31 19:49
> please change line 731 in sim_timer.c

Hello, there doesn't seem to be such a line in that file. As I grep the source code I find such a line does exist in <code>./VAX/vax780_stddev.c</code> as line 731. I should edit that file instead?

**Comment by markpizz** [comment] 2017-01-31 19:50
Sorry.  You have found the correct place in the correct file.

**Comment by porcupixel** [comment] 2017-01-31 20:40
Thank you, @markpizz. I have made that change to <code>VAX/vax780_stddev.c</code>. Running with the default kernel looks good so far. It's only been running about 20 minutes as I write this but shows no evidence of drift.

Next trick I will edit <code>/usr/src/sys/h/param.h</code> in 32V which contains:

> #define HZ      60              /* Ticks/second of the clock */

I'll change this to 50, recompile the kernel, and see what happens. Do you want the 50Hz kernel tested both with and without the change to <code>VAX/vax780_stddev.c</code>?

**Comment by markpizz** [comment] 2017-01-31 20:42
Testing both 50Hz and 60Hz with the changed vax780_stddev.c is sufficient.

Thanks.

**Comment by markpizz** [comment] 2017-01-31 20:55
You may want to confirm that the 50Hz kernel's timekeeping is way off with the older simh vax780 simulator from your distro.  @WILLIAMCORCORAN reported that problem a while back and that was fixed.  Your exercise now with the 50Hz test is merely to confirm that change for the 60Hz doesn't introduce a regression.

**Comment by porcupixel** [comment] 2017-01-31 21:22
Thank you, @markpizz. When testing the 60Hz kernel I forgot to mention that pressing Ctrl-E while the system was running and then <code>show clock</code> reports:
>   Running at:                60 Hz

After making the change I described in <code>/usr/src/sys/h/param.h</code> I recompiled the kernel with <code>make unix</code>, moved the resulting file to /, and killed the emulator after syncing disks. After booting again it, too, seems fine. It ran about 10 minutes and kept precise time with the host system's clock although pressing Ctrl-E and then show clock still reports:
>   Running at:                60 Hz

I am not sure if it's supposed to report 50 Hz there?

**Comment by markpizz** [comment] 2017-01-31 21:27
We're on the right track with the 60Hz case.

Meanwhile as for your 50Hz test, it seems that /usr/src/sys/h/param.h isn't where you need to change things.  The SHOW CLOCK output you see is based on the value the OS programs into the interval timer, so if it says 60Hz, then it seems to be programming the same value.

@WILLIAMCORCORAN originally reported the 50Hz problem.  Bill, do you recall how/what you changed to build the 50Hz kernel?

**Comment by porcupixel** [comment] 2017-01-31 21:30
Oh, I forgot to mention that I am not able to boot 32V using the version provided by my distro (only ITS in a PDP-10 which showed a similiar problem with lost time although I no longer have ITS set up on a PDP-10 for testing.) With the vax780 binary from my distro trying to boot 32V does start the bootloader but once you enter 'unix' as the name of the kernel file to boot it dies:

> TRAP FROM KERNAL MODE
> HALT instruction, PC: 8000043B (HALT)

This is why I am running from git master, because it includes the changes needed in order to run 32V at all.

**Comment by markpizz** [comment] 2017-01-31 21:35
I thought that you originally mentioned that you got the same results with the distro vax780 binary.

I thought that the only real change that was 32V specific related to actually idling correctly with the new code while the older versions didn't idle with 32V.  Oh well.  Never mind about testing the old case.  Whatever problem existed is clearly fixed now.

We still want to find a way to test 50Hz though.

**Comment by porcupixel** [comment] 2017-01-31 21:39
"I thought that you originally mentioned that you got the same results with the distro vax780 binary."
Yes, when I said "I should also add that I've noticed this loss of time both when running the version of simh provided by my distro and when running from git master (git commit id: d14243c)" I was referring to seeing the loss of time on ITS on a PDP-10 and in 32V on the VAX, trying to say it was a common theme among at least the two different machines. I didn't mean to cause any confusion there. Sorry.

**Comment by markpizz** [comment] 2017-01-31 22:08
I'm confident in the simh provided timing facilities being very accurate.  As we're seeing they only provide good results when they're given correct inputs though.  Therefore, if ITS (on the PDP10) also has a problem, then the input value it is giving the timing services may also be computed slightly incorrectly.   Timekeeping on the PDP10 is a separate problem which should be explored separately.

Meanwhile, some others have suggested (and I agree) that the more mathematically correct expression for the tps calculation is:
```clk_tps = (int32)((1000000.0 / usecs) + 0.5);```

To be complete, please test with this and let me know if you're able to kernel that actually runs at 50Hz.

**Comment by porcupixel** [comment] 2017-02-01 02:03
Making the change to <code>clk_tps = (int32)((1000000.0 / usecs) + 0.5);</code> also seems to work without issue. The time seems accurate, and show clock shows running at 60 Hz and the number of ticks and ticks acked are the same.

**Comment by markpizz** [comment] 2017-02-01 02:11
Hmmm...  It seems that @WILLIAMCORCORAN never actually ran with a 50Hz clock.  His issue with the clock (#253) was merely that the 60Hz clock didn't track time correctly.  The math works for 60Hz, in the 50Hz case, the interval usecs value will be 20000 and the math for that number produces 50Hz, and the math for the 100Hz case (10000 usecs) produces 100Hz, so that is good enough for me.

**Closed** 2017-02-01 02:16 UTC

**Comment by WILLIAMCORCORAN** [comment] 2017-02-01 04:34
Hello Mark,

If I remember correctly, my issue at the time, was not not a slight and slow drift of the system clock.  Rather, it was a substantial difference where sleep would prematurely return clean in half the time.  

I will pull my notes on this and repeat the tests to see if this is still an issue.  I have been sidetracked working on a BSD 2.11 issue where calling /bin/true within a loop will intermittently fail with  "/bin/true cannot execute."

I am working closely with a brilliant TUHS member that is interested in helping me resolve the BSD 2.11 issue.  

If I determine that (#253) is still an unresolved issue, then I will see if my TUHS  friend is willing to provide any advice on that issue as well. 

I am sorry that I have not made progress on (#253) since I am putting every resource on fixing the BSD 2.11 SIMH issue (on top of daily life). 

Finally, I will review my notes on the status of (#253) and if i find anything interesting, I will post it here.  
Moreover, if (#253) is no longer an issue after repeating the tests, I will close the case.   


Truly,

Bill Corcoran

>
