### ISSUE TITLE
SIMH PDP11 RT-11 5.03 & TSX 6.01 Clock Issue

### ISSUE THREAD

**Issue by pverdet** [simh/simh#368] opened 2016-12-23 15:00 UTC
After some investigations, I configure simh as follow:
CPU     11/73, NOCIS, idle disabled, autoconfiguration enabled
        256KB
SYSTEM
RHA     disabled
RHB     disabled
RHC     disabled
CLK     50Hz, address=17777546-17777547, vector=100
PCLK    disabled
RL      RLV12, address=17774400-17774411, vector=160, 4 units
  RL0   5242KW, attached to RT-11 V5.3 WORKING.DSK, on line
        write enabled, RL02
  RL1   5242KW, attached to TSX601.DSK, on line
        write enabled, RL02
  RL2   2621KW, not attached, on line
        write enabled, autosize
  RL3   2621KW, not attached, on line
        write enabled, autosize

Boot on RL0 and SYSGEN RT-11 with 
26.  Do you want the optional 50 Hz clock support (N)? Y

.sh conf

RT-11FB (S) V05.03
Booted from DL0:RT11FB

USR   is set SWAP
EXIT  is set SWAP
KMON  is set NOIND
TT    is set NOQUIET
ERROR is set ERROR
SL    is set OFF
EDIT  is set KED
KMON nesting depth is 3
Global .SCCA flag is disabled

PDP 11/73A Processor
256KB of memory
Floating Point Microcode
Extended Instruction Set (EIS)
Memory Management Unit
Cache Memory
50 Cycle System Clock  <==

.date
23-Dec-2016

.time
15:20:27

.R TSX
?TSX-F-Computer line time clock (50 or 60 Hz) is not working        ????

.
Simulation stopped, PC: 153012 (BR 153002)
sim>
I enable PCLK :
sim> set pclk enable
sim> set pclk 50
sim> sh pclk
PCLK    100K Hz, address=17772540-17772545, vector=104 50 Hz Line Frequency

SYSGEN with 
26.  Do you want the optional 50 Hz clock support (N)? Y
27.  Do you want to use the KW11-P clock as the system clock (N)? Y

.sh conf

RT-11FB (S) V05.03
Booted from DL0:RT11FB

USR   is set SWAP
EXIT  is set SWAP
KMON  is set NOIND
TT    is set NOQUIET
ERROR is set ERROR
SL    is set OFF
EDIT  is set KED
KMON nesting depth is 3
Global .SCCA flag is disabled

PDP 11/73A Processor
256KB of memory
Floating Point Microcode
Extended Instruction Set (EIS)
Memory Management Unit
Cache Memory
50 Cycle System Clock  <===

.date
23-Dec-2016

.time
15:43:24

.R TSX

HALT instruction, PC: 122010 (HALT)
sim>

The simulator crash. It seems that the problem lies around the management of the clock ?
Cheers

**Comment by pverdet** [comment] 2016-12-23 15:53
Try with XXDP V2.5
XXDP-XM EXTENDED MONITOR - XXDP V2.5
REVISION: F0
BOOTED FROM DL0
124KW OF MEMORY
NON-UNIBUS SYSTEM

RESTART ADDRESS: 152000
TYPE "H" FOR HELP !

.LOAD ZKWBJ1
ZKWBJ1.BIC

.START
ìèCZKWBJ KW11-P RT CLK TSTì
HALT instruction, PC: 001332 (BR 1254)

**Comment by markpizz** [comment] 2016-12-30 22:52
Hi Pascal,

In general, there never has been a goal for the simh DEC simulators to actually pass DEC diagnostics.  The goal has been to get operating system and application software to work.

That said, if diags work, then that would never negatively impact the goal of having operating system and application software working if some of the diags also worked.

I tried your test with XXDP V2.5.  Since you didn't provide the details of how you actually started the diag, I'm not sure what you were seeing.  I get the result you got if I fail to enable the the PCLK device.  Without the device enabled it would be hard to imagine we would expect the diagnostic for it to work.

When I actually enabled the device, the simulator hung (and couldn't even be stopped with ^E).  This was a bug in the implementation of the PCLK device.  I fixed that problem and the current PCLK device now behaves the same as the simh 3.9 PCLK device in the PDP11 simulator.  If you read the source to the pdp11_pclk.c device simulation, you'll see this comment:

      Use XXDP V2.5 test program ZKWBJ1.BIC; loads at 1000, starts at
      1100?  Seems to execute the first few tests correctly then waits
      for input from the console.  I don't have a description of how this
      diagnostic works and thus don't know how to proceed from that point.

If you know more about how to run this diagnostic, please advise.

Meanwhile, the problem you were originally seeing under RT11 attempting to run TSX wasn't the problem I just fixed due to the diagnostic.  In the past couple of weeks there were other issues with the simh timing capabilities, which have been also been fixed.

Please try the TSX test again, but since I'm not sure you've gotten TSX to run at all yet, the timing issues may also not get you going.

- Mark

**Comment by pverdet** [comment] 2016-12-31 10:32
Thanks Marc. I will try to test asap.
Happy new year.

**Comment by pverdet** [comment] 2017-01-04 19:37
Hi,
Using new version 
PDP-11 simulator V4.0-0 Beta        git commit id: d77e3e19
sim> sh ver
PDP-11 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                32b data
                32b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 2
        Host Platform:
                Compiler: Microsoft Visual C++ 15.00.30729.01
                Simulator Compiled as C arch: x86 (Release Build) on Jan  2 2017 at 14:08:55
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.5
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: Microsoft Windows [version 10.0.14393]
                Architecture: x86 on AMD64, Processors: 2
                Processor Id: AMD64 Family 16 Model 6 Stepping 2, AuthenticAMD, Level: 16, Revision: 0602
        git commit id: d77e3e19

With minimum configuration
sim>  sh conf
PDP-11 simulator configuration
CPU     11/23, FPP, NOCIS, BEVENT enabled, idle disabled, autoconfiguration enabled   256KB
SYSTEM
CLK     50Hz, address=17777546-17777547, vector=100
TTI     address=17777560-17777563, vector=60         7b
TTO     address=17777564-17777567, vector=64        7p
LPT     address=17777514-17777517, vector=200       not attached
RL      RLV12, address=17774400-17774411, vector=160, 4 units
  RL0   5242KW, attached to RT-11 V5.3 WORKING.DSK, on line         write enabled, RL02
Booting RT-11 V5.3
sh conf

RT-11FB (S) V05.03
Booted from DL0:RT11FB

USR   is set SWAP
EXIT  is set SWAP
KMON  is set NOIND
TT    is set NOQUIET
ERROR is set ERROR
SL    is set OFF
EDIT  is set KED
KMON nesting depth is 3
Global .SCCA flag is disabled

PDP 11/23 Processor
256KB of memory
FP11 Hardware Floating Point Unit
Extended Instruction Set (EIS)
Memory Management Unit
**50 Cycle System Clock  <<==**

.date
4-Jan-2017

.time
20:18:48
.time
20:20:03 (Working clock ?)

.r tsx
?TSX-F-Computer line time clock (50 or 60 Hz) is not working

The problem seam the same (Sorry) :-(

Booting xxdp25
sim> boot RL0
BOOTING UP XXDP-XM EXTENDED MONITOR

XXDP-XM EXTENDED MONITOR - XXDP V2.5
REVISION: F0
BOOTED FROM DL0
124KW OF MEMORY
NON-UNIBUS SYSTEM

RESTART ADDRESS: 152000
.LOAD ZKWBJ1.BIC
ZKWBJ1.BIC

.START

CZKWBJ KW11-P RT CLK TST
HALT instruction, PC: 001332 (BR 1254)

Crazy, No ?

**Comment by markpizz** [comment] 2017-01-04 19:43
Please provide a configuration file which reproduces each of the above mentioned failures (RT11 and XXDP) and provide the disk images (or pointers to them) that you are booting from in each case.

**Comment by pverdet** [comment] 2017-01-05 20:07
Config file : Work.ini, and two disks (RT-11 V5.3 & XXDP25) zipped on PDP-files.zip
https://1fichier.com/?8i8pb9leit
Thanks.

**Comment by pverdet** [comment] 2017-01-05 20:44
Hi Marc,
May be is a mistake from me. Looking for tests, I found :
https://archive.org/stream/bitsavers_decpdp11xxndbook1988_9334162/PDP11_DiagnosticHandbook_1988_djvu.txt
- ZKWBJ1 

**KW11-P** PROGRAM. REAL TIME CLOCKL TEST 
ABSTRACT : 

This diagnostic verities proper operation oi the KWUP. It contains a series 
of incremental routines that test the control and status register, count set 
buffer, counter, and interrupt vector address using 100 KHz, lOKHz line and 
external frequencies.

Trough my searches, I found :
http://www.chdickman.com/pdp11/xxdp25.notes.txt
==>ZKWA		LINE FREQUENCY CLOCK TEST

BOOTING UP XXDP-XM EXTENDED MONITOR
XXDP-XM EXTENDED MONITOR - XXDP V2.5
REVISION: F0
BOOTED FROM DL0
124KW OF MEMORY
NON-UNIBUS SYSTEM

RESTART ADDRESS: 152000
TYPE "H" FOR HELP !

.LOAD ZKWA??
ZKWAG0.BIC

.START

  CZKWA-G LINE FREQUENCY CLOCK TEST

  END PASS #     1  
                                  LKS     LKS
  (PC)    (PS)    (SP)    TEST#   WAS     S/B
  002626  000244  000770  000010  000000  000300

                                  LKS     LKS
  (PC)    (PS)    (SP)    TEST#   WAS     S/B
  003026  000304  000770  000011  000100  000300

It seems that it works normally !!! ? but some time we have an error :   
END PASS #     2  
                                  LKS     LKS
  (PC)    (PS)    (SP)    TEST#   WAS     S/B
  002116  000004  000770  000004  000000  000200

                                  LKS     LKS
  (PC)    (PS)    (SP)    TEST#   WAS     S/B
  002204  000344  000770  000005  000000  000100

                                  LKS     LKS
  (PC)    (PS)    (SP)    TEST#   WAS     S/B
  002314  000344  000770  000006  000000  000000

  **CLOCK FAILED TO INTERRUPT**
  (PC)    (PS)    (SP)    TEST#   (LKS)
  002470  000004  000770  000007  000100

  **CLOCK FAILED TO INTERRUPT**
  (PC)    (PS)    (SP)    TEST#   (LKS)
  002650  000244  000770  000010  000100

**Comment by markpizz** [comment] 2017-01-05 20:50
Please look closely at your ini file.  Notice that you haven't enabled the PCLK device.  The PCLK device is disabled by default.  Without the device in the system configuration it isn't the least bit surprising that it doesn't even get started in the diagnostic.

I said the same thing earlier.

Meanwhile, if you want TSX to use the PCLK device, you've ALSO got to enable it first.

As I've said in other issues, I have no idea what TSX actually needs to run, nor if it is able to run with the hardware configuration you described.

The diagnostic notes you've found are running test ZKWAG0 which DOES NOT test the PCLK device.  It tests the CLK device (Line Frequency Clock).

As for the potential problem with the Line Frequency Clock device diagnostic, Please provide the version of the simh software you were running to produce the above results.

**Comment by pverdet** [comment] 2017-01-05 21:06
sim> sh ver
PDP-11 simulator V4.0-0 Beta
        Simulator Framework Capabilities:
                32b data
                32b addresses
                Ethernet Packet transports:PCAP:NAT:UDP
                Idle/Throttling support is available
                Virtual Hard Disk (VHD) support
                RAW disk and CD/DVD ROM support
                Asynchronous I/O support
                Asynchronous Clock support
                FrontPanel API Version 2
        Host Platform:
                Compiler: Microsoft Visual C++ 15.00.30729.01
                Simulator Compiled as C arch: x86 (Release Build) on Jan  2 2017 at 14:08:55
                Memory Access: Little Endian
                Memory Pointer Size: 32 bits
                Large File (>2GB) support
                SDL Video support: SDL Version 2.0.5
                PCRE RegEx support for EXPECT commands
                OS clock resolution: 1ms
                Time taken by msleep(1): 1ms
                OS: Microsoft Windows [version 10.0.14393]
                Architecture: x86 on AMD64, Processors: 2
                Processor Id: AMD64 Family 16 Model 6 Stepping 2, AuthenticAMD, Level: 16, Revision: 0602
        git commit id: d77e3e19

for me the tsx message 
Computer line time clock (50 or 60 Hz) is not working , means that the TSX wait for interrupt, and don't receive them .
![image](https://cloud.githubusercontent.com/assets/23553379/21697555/3067c0e4-d393-11e6-9271-9f37c5717cc3.png)
![image](https://cloud.githubusercontent.com/assets/23553379/21697563/41dec430-d393-11e6-943b-c358ab9551d8.png)

**Comment by markpizz** [comment] 2017-01-05 21:37
There is a reason we explicitly don't try to get diagnostics running.

The primary reason is that the diagnostics were written explicitly to run on real hardware and report hardware errors that may actually exist in that environment.  They weren't meant to run on modern systems with simulated hardware that runs at least 10's of times faster than the original hardware ever did.  My desktop system (running non optimized PDP11 code) executes PDP11 instructions at almost 50 MIPS.  

The diagnostics were written to run on hardware which executed 100's of KIPS.  The clock diagnostic would likely have a timing loop which on the real hardware would take a good number of clock ticks before the loop counter was exhausted and that would probably be how it is testing for interrupts occurring.  On the simulator the whole loop executes in less than a single clock tick and thus the diagnostic concludes that an interrupts don't work since one didn't occur before the reasonable timing loop completed.

First you should upgrade to the latest code.  There have been recent timing related changes which may or may not affect the behavior you are seeing.

Second, you should run with this configuration to demonstrate to yourself that the Line Frequency Clock works.

    att rl0 xxdp25.rl02
    set throttle 300k
    set quiet
    expect "\n." send "LOAD ZKWAG0\r" ; GO
    expect "\n." send "START\r" ; GO
    boot rl0

**Comment by pverdet** [comment] 2017-01-06 16:31
You have rights. I forget to many times that today we have more power in a phone, than an 11/73 :-(
I set throttle 300k ...
The diag work as design. No problem ...
In other side, we retrieve the same problem with TSX : 
.R TSX
?TSX-F-Computer line time clock (50 or 60 Hz) is not working
I think may be TSX do a system call to read the line time clock register, and the simulator don't implement or support the call ?

**Comment by markpizz** [comment] 2017-01-06 18:58
I have no idea and why this may be happening, but the simulator supports devices and then operating systems run on the simulator and those either have drivers or not for particular devices.  At this point solving this would be an effort most easily resolved with TSX source code and source for the RT11 version you're working with.  

From the point of view of the simh project, this is not a simulator problem until you can clearly demonstrate (with source code) that the simulator or one of its devices doesn't behave the way the original hardware did.  If you don't have source code, then you are on your own to dig further into what may be happening.

Good Luck.

I'm closing this issue for now until you can point specifically at a simulator issue.  Please reopen it if you have more useful information.

**Closed by markpizz** 2017-01-06 18:58 UTC

**Comment by kolloid** [comment] 2017-03-03 22:27
I have experienced this same problem since several years back, when computers started to be too fast for the initial detection loop of TSX11-Plus. I solved this putting a software delay between instructions in the PDP-11 code ... a rather lousy fix but it worked.

Starting with SIMH 3.9 (I think) this problem can be fixed using the THROTTLE command.
I put:
SET THROTTLE 1%
in my cnf file. After RT-11 boots, TSX11 starts normally. I stop the emulator with ^e and set throttle to some higher value, say 50%. Then I continue with the C command. Evidently TSX11 only checks the clock speed once, when starting.
I wonder if this sequence of operations could be automatized somehow, but at least it works.

**Comment by markpizz** [comment] 2017-03-03 23:49
If it merely is a speed problem, and throttling can be used to get useful functionality, then it should be pretty easy to automate.  The configuration file would be normal up to just before the BOOT command and there you'd have:
```
sim> set throttle 1%
sim> expect "some-string-emitted-after-timing-loop" set throttle 50% ; GO
sim> boot rl0
```

I know nothing about TSX, but once you get it running with a 1% throttle, the appropriate value to put between the quotes should be simple to determine.

**Comment by kolloid** [comment] 2017-03-04 09:55
Thanks! I was under the impression that EXPECT could be used only to stop the emulation, now I see that it can be started again. Nice ...

For now I cannot test it, because SIMH 3.9 does not have EXPECT, and the pdp11 emulator of SIMH 4.0 has some problem in my machine and doesn't boot RT-11. I will look into it and will open a new issue later.

**Comment by pverdet** [comment] 2017-03-06 09:38
Thanks Kolloid,
I will try to test asap your patch.

**Comment by kolloid** [comment] 2017-03-06 10:46
I hope it helps, Pverdet. Let me know. For me it works, even if from time to time TSX still refuses to start at first. But the next time it starts.

**Comment by pverdet** [comment] 2017-03-06 17:53
Hi Kolloid,
Please can you send me your mail address ?
Thanks
Pascal

**Comment by markpizz** [comment] 2017-03-06 18:00
I'll be a conduit for email delivery since my email address is visible here many times.  So, @kolloid you can send email to me mark@infocomm.com and I'll pass it on to Pascal.

Meanwhile, @kolloid, will you please put your full name on in your Github profile so we can know who we're actually talking to.  

Thanks.

**Comment by kolloid** [comment] 2017-03-06 19:44
Sorry, I didn't remember that my profile was practically empty. I just updated it.
Mark, I sent you a PM so you can give my email to Pascal.

Thanks
Tom

**Comment by markpizz** [comment] 2017-03-06 19:58
Well, I thought I had Pascal's email address.  I don't so, @pverdet if you send me your address I'll pass it on to Tom and I'll send you Tom's.

**Comment by pverdet** [comment] 2017-03-08 11:03
Thanks to Tom for the patch. Work as design.
* TSX-Plus Version 6.2 *
Line # 1

.sh dev
        Active          Handler  Handler  Handler
Device    I/O   Status  V. base  P. base   size     CSR    Vector
------  ------  ------  -------  -------  -------  ------  ------
  TT        0   000004
  LD        0   102446
  CL        0   006057   034164   000000    254
  DL        0   102405   120000   006057   1418    174400  160
  LP        0   030003   120000   006050    406    177514  200
  NL        0   000025   120000   006047     60
.w
Uptime: 00:02:47
System use:   Run=86%, I/O-wait=0%, Swap-wait=0%, Idle=13%
I/O Activity: User I/O=0%, Swapping I/O=0%

Job   Line   Pri   State    Size   Connect   CPU time  Program    Job name
---  ------  ---  -------  -----  ---------  --------  -------  ------------
 1*   1(0)    50  IN        36Kb   00:01:00  00:02:24  KMON

Thanks also to Mark for help.

**Comment by pverdet** [comment] 2017-03-11 14:45
Hi Guys,
Finally, I found the root cause : 
![image](https://cloud.githubusercontent.com/assets/23553379/23824143/6dadb06a-0671-11e7-8414-a38754853bdb.png)
During initialization TSX loads the date and time.
The next statement is to compare it. The simulator is so fast, the time does not change ...
Thanks to Tom and Mark for their help.

**Comment by kolloid** [comment] 2017-04-02 14:39
Hi Pascal,

So that is the code. It should be possible to patch it, putting an unconditional branch instead of the BNE.

Best
Tom
