### ISSUE TITLE
Add PDP-9 postbuild diags

### ISSUE THREAD

**Issue by mgthompson** [simh/simh#831] opened 2020-04-02 01:05 UTC
I saw that the PDP-8 and VAX has postbuild diagnostics. I created a pdp9_test.ini file based on the PDP-8 and VAX files, and Visual Studio will run six PDP-9 MAINDECs. How do I submit the MAINDEC files?

- #### It works with PDP-9 simulator V4.0-0 Current        git commit id: 61431805

2>    Post-Build-Event.cmd PDP18B "E:\simh.SVN\trunk\BIN\NT\Win32-Debug\PDP9.exe"
2>    :VCEnd
2>     Running internal register sanity checks on PDP-9 simulator.
2>    *** Good Registers in PDP-9 simulator.
2>
2>
2>    PDP-9 simulator V4.0-0 Current        git commit id: $Format:
2>
2>    Running MAINDEC-9A-D01A PDP-9 Instruction Test 1: Passed
2>    Running MAINDEC-9A-D02A PDP-9 Instruction Test 2: Passed
2>    Running MAINDEC-9A-D0DB PDP-9 JMP-Self Test: Passed
2>    Running MAINDEC-9A-D0EA PDP-9 JMP Y - Interrupt Test: Passed
2>    Running MAINDEC-9A-D0FA PDP-9 JMS Y - Interrupt Test: Passed
2>    Running MAINDEC-9A-D0BA PDP-9 ISZ Test: Passed
2>
2>    !! All Tests Passed !!

- #### I created this pdp9_test.ini file to run the diagnostics.
:: pdp9_test.ini
::
:: Run the paper tape-based diagnostics for the PDP-9 simulator.
::
:: Maximum memory, Extended Arithmetic Element
set cpu 32k
set cpu eae

cd %~p0
:: Limit maximum diagnostic execution time
::
set runlimit 2 minutes
set on
on error ignore
on runtime echof "\r\n*** Test Runtime Limit %SIM_RUNLIMIT% %SIM_RUNLIMIT_UNITS% Exceeded ***\n"; exit 1

:: LAC, TAD, ADD, SAD, XOR and all Operate instruction test (D01A)
echof -n "\rRunning MAINDEC-9A-D01A PDP-9 Instruction Test 1: "
if not exist diags/maindec-9a-d01a-ph.rim echof "\r\nMISSING - Diagnostic '%~p0maindec-9a-d01a-ph.rim' is missing\n"; exit 1
load diags/maindec-9a-d01a-ph.rim 22
:: Break at 13030 to stop execution after a full pass is done.
nobreak all
break 13030
go -q 13041
if (PC != 013030 || AC != 000000) echof "Failed."; ex pc; ex ac; exit 1
echof "Passed"

:: DZM, DAC, ISZ, JMP, CAL, JMS, XCT, Autoindex, Indirect, Time Clock, PI, DBR (D02A)
echof -n "Running MAINDEC-9A-D02A PDP-9 Instruction Test 2: "
if not exist diags/maindec-9a-d02a-ph.rim echof "\r\nMISSING - Diagnostic '%~p0maindec-9a-d02a-ph.rim' is missing\n"; exit 1
load diags/maindec-9a-d02a-ph.rim 22
:: Break at 6256 to stop execution after a full pass is done.
nobreak all
break 6256
go -q 6265
if (PC != 006256 || AC != 000000) echof "Failed."; ex pc; ex ac; exit 1
echof "Passed"

:: JMP Self (D0DB)
echof -n "Running MAINDEC-9A-D0DB PDP-9 JMP-Self Test: "
if not exist diags/maindec-9a-d0db-ph.rim echof "\r\nMISSING - Diagnostic '%~p0maindec-9a-d0db-ph.rim' is missing\n"; exit 1
load diags/maindec-9a-d0db-ph.rim 17500
:: Break at 17521 to stop execution after a full pass is done.
nobreak all
break 17521
go -q 17500
if (PC != 017521 || AC != 000000) echof "Failed."; ex pc; ex ac; exit 1
echof "Passed"

:: JMP Self (D0EA)
echof -n "Running MAINDEC-9A-D0EA PDP-9 JMP Y - Interrupt Test: "
if not exist diags/maindec-9a-d0ea-ph.rim echof "\r\nMISSING - Diagnostic '%~p0maindec-9a-d0ea-ph.rim' is missing\n"; exit 1
load diags/maindec-9a-d0ea-ph.rim 17400
:: Break at 17474 to stop execution after a full pass is done.
nobreak all
break 17474
go -q 17400
if (PC != 017474) echof "Failed."; ex pc; ex ac; exit 1
echof "Passed"

:: JMP Self (D0FA)
echof -n "Running MAINDEC-9A-D0FA PDP-9 JMS Y - Interrupt Test: "
if not exist diags/maindec-9a-d0fa-ph.rim echof "\r\nMISSING - Diagnostic '%~p0maindec-9a-d0fa-ph.rim' is missing\n"; exit 1
load diags/maindec-9a-d0fa-ph.rim 17400
:: Break at 17512 to stop execution after a full pass is done.
nobreak all
break 17512
go -q 17400
if (PC != 017512) echof "Failed."; ex pc; ex ac; exit 1
echof "Passed"

:: JMP Self (D0BA)
echof -n "Running MAINDEC-9A-D0BA PDP-9 ISZ Test: "
if not exist diags/maindec-9a-d0ba-ph.rim echof "\r\nMISSING - Diagnostic '%~p0maindec-9a-d0ba-ph.rim' is missing\n"; exit 1
load diags/maindec-9a-d0ba-ph.rim 100
:: Break at 144 to stop execution after a full pass is done.
nobreak all
break 144
go -q 100
if (PC != 000144 || AC != 000000) echof "Failed."; ex pc; ex ac; exit 1
echof "Passed"

echof
echof "!! All Tests Passed !!"
echof
exit 0

**Comment by markpizz** [comment] 2020-04-02 15:53
Thanks for doing this.

You can zip up the diagnostics and drop the zip file into this issue.  I'll take it from there.  I will credit you as author if you send me privately (to mark@infocomm.com) your email address which I'll use in the commit.

------
Separately, I see in your output above:
> 2> PDP-9 simulator V4.0-0 Current git commit id: $Format:

The commit id shouldn't be $Format.  What version of Visual Studio are you using AND how did you get the simh source onto the system you built on?

**Comment by mgthompson** [comment] 2020-04-02 23:40
The ini file and the Maindec paper tape images are attached.
[tests.zip](https://github.com/simh/simh/files/4424292/tests.zip)

My email is mike@ricomputermuseum.org

I am using Visual Studio 2017 Community.

I used GIT to get the source. I opened the solution and allowed VS to upgrade the projects to VS2017. I had to change the Windows SDK version in the projects to 10.0.17763.0 to get them to build.

The output from the build says: PDP-9 simulator V4.0-0 Current        git commit id: $Format:
If I run the simulator outside of VS it says; PDP-9 simulator V4.0-0 Current        git commit id: 61431805

**Comment by markpizz** [comment] 2020-04-03 00:43
Before this gets committed, I see that you're comments describe these as Paper Tape diagnostics, but you don't use the system Paper Tape reader to load them.  More pieces of the simulator would be exercised if some, if not all, of these were actually read from the PTR device.

Also, your error messages which are emitted if the diagnostic files can't be found, incorrectly leave out "diag/" as part of the path to the diagnostics...

Thoughts?

-----
You say:
> The output from the build says: PDP-9 simulator V4.0-0 Current git commit id: $Format:
> If I run the simulator outside of VS it says; PDP-9 simulator V4.0-0 Current git commit id: 6143180

If you are seeing this, then you're not executing the same binaries.

> I used GIT to get the source. I opened the solution and allowed VS to upgrade the projects to VS2017. I had to change the Windows SDK version in the projects to 10.0.17763.0 to get them to build.

After you pick up the latest codebase (which won't be a simple "git pull" since the previous VS conversion will have modified simh.sln and thus a pull won't complete.  You should either "git clone" into new separate directory and start the conversion again, or do a "git reset --hard HEAD^" followed by a "git pull".  Many changes are made to the VS2008 projects as time goes by and you won't get the effects of these changes in VS2017 unless you do the conversion from VS2008 to VS2017 again.

Using the latest codebase, I just opened simh.sln using VS2017 and after the conversion completed, I simply compiled the PDP9 simulator without having to adjust any Windows SDK version.

FYI: git commit id: 6143180 was more than 6 months ago (9/19/2019).

The first line in the build output you provide above says:
>2> Post-Build-Event.cmd PDP18B "E:\simh.SVN\trunk\BIN\NT\Win32-Debug\PDP9.exe"

Somehow this suggests that SVN rather than git is part of the picture here...

**Comment by mgthompson** [comment] 2020-04-03 13:25
I deleted the source, downloaded new source into a directory named SIMH, and now it says "2>PDP-9 simulator V4.0-0 Current        git commit id: f8a369e6"

I don't have the VS 8.1 SDK installed, so I upgraded all of the projects to the 10.0.17763.0 SDK. The build worked OK for all of the projects with the newer SDK.

There are Paper Tape Reader, Paper Tape Punch, EAE, Floating Point, DECtape, Disk, Magnetic Tape, Graphics, Serial Port, Line Printer, etc. diagnostics available. With a lot more work I could likely get these to work. I would be happy to work on getting more diagnostics to run if you want to delay incorporating these diags.

The corrected pdp9_test.ini file with "diag/" added is attached.
[pdp9_test.zip](https://github.com/simh/simh/files/4427436/pdp9_test.zip)

**Comment by markpizz** [comment] 2020-04-03 14:52
> There are Paper Tape Reader, Paper Tape Punch, EAE, Floating Point, DECtape, Disk, Magnetic Tape, Graphics, Serial Port, Line Printer, etc. diagnostics available. With a lot more work I could likely get these to work. I would be happy to work on getting more diagnostics to run if you want to delay incorporating these diags.

I wasn't suggesting that you run different/additional diags, but merely that you use the PTR to load the paper tape images.  The only reason this comes up is due to the fact that there recent;y (within the past 2 or so weeks) a case where someone using one of the other DEC simulators got unexpected behavior when using a paper tape reader under certain conditions.  Having a test that merely used the PTR device would possibly exercise that sort of stuff and also reflect more closely how this stuff was originally used.  

Maybe I am naive, since I know almost nothing about using the PDP9 simulator, but wouldn't just replacing:
```
load diags/maindec-9a-d01a-ph.rim 22
go -q 13041
```
with something like:
```
attach ptr diags/maindec-9a-d01a-ph.rim 
boot ptr
```
do the trick?

**Comment by mgthompson** [comment] 2020-04-03 17:56
Now booting the diags from the paper tape reader.

[pdp9_test.zip](https://github.com/simh/simh/files/4429062/pdp9_test.zip)

**Closed** 2020-04-13 18:31 UTC
