### ISSUE TITLE
Device use comment / advice sought

### ISSUE THREAD

**Issue by al20878** [simh/simh#1034] opened 2021-04-16 00:19 UTC
- #### Context
```
sim> att -re tc dos005.dta
TC: unit is read only
TC0: 16b format, buffering file in memory
sim> sh tc
TC      address=17777340-17777351, vector=214, BR6, 8 units
  TC0   147KW, attached to dos005.dta, read only, write enabled
        16b
```
I don't know where else to ask so I'm creating an issue but it's merely a question (is there a discussion group /thread about simh anywhere, BTW?)

First, I don't understand how to read this: ``read only, write enabled`` -- as to me, it's either one or the other.

Second,
```
TC: unit is read only
TC0: 16b format, buffering file in memory
```
this part is inconsistent -- looks like the entire ``TC`` was set read-only, because the second line suggests that the unit number is printed (even as 0) when the specific unit is concerned.

Third, when I attach the ``tc0`` without the ``-r`` flag, and nothing was actually written to it (it was only read), when I quit the simulator, the following appears:
```
sim> q
Goodbye
TC0: writing buffer to file
```
Why would it write the file that was never changed?

Thanks.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
sim> show ver
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Polled Ethernet Packet transports:PCAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 10.2.0
        Simulator Compiled as C arch: x64 (Release Build) on Apr 12 2021 at 12:27:46
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        No RegEx support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: libpcap not installed
        OS: CYGWIN_NT-6.1  3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin
        tar tool: tar (GNU tar) 1.34
        curl tool: curl 7.75.0 (x86_64-pc-cygwin) libcurl/7.75.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.0.4) libssh2/1.7.0 nghttp2/1.37.0
        git commit id: 371c937e
        git commit time: 2020-03-12T02:17:19-0400
```
- #### how you built the simulator or that you're using prebuilt binaries

``make pdp11``
- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment] 2021-04-16 18:34
> I don't know where else to ask so I'm creating an issue but it's merely a question (is there a discussion group /thread about simh anywhere, BTW?)

I would say that a question like this (due to confusing information being presented to the user) belongs here since to correct the general confusing info, code will need to be changed.

So your first question:

> sim> att -re tc dos005.dta
> TC: unit is read only
> TC0: 16b format, buffering file in memory
> sim> sh tc
> TC      address=17777340-17777351, vector=214, BR6, 8 units
>   TC0   147KW, attached to dos005.dta, read only, write enabled
>         16b
>
> I don't understand how to read this: read only, write enabled -- as to me, it's either one or the other.

How true! 

The "TC: unit is read only" message is generated deep within a general open file API and you could consider it related to whatever mechanism media of this type did to enable write or read-only (like a write ring on a 9-track tape).  I've changed that API to emit the appropriate unit name on these messages.  

Meanwhile, the "write enabled" or it's converse "write locked" represents some aspect of how the simulated software may have setup access to the device.  It does seem reasonable that the physical write enable/disable on the media would override the software setting.  As it turns out, for this device, there is no formal software command to write lock the tape device, but there is a SCP command SET TCn LOCKED.  I've cleaned up the functionality so things are more consistent.

Your second question:

> TC: unit is read only
> TC0: 16b format, buffering file in memory
> this part is inconsistent -- looks like the entire TC was set read-only, because the second line suggests that the unit number is printed (even as 0) when the specific unit is concerned.

simh device names allow for TC and TC0 to be equivalent to each other when specifying unit 0 of a device.  Had your input been more specific and said, TC0 rather than merely TC your understanding may have been clearer.  As mentioned above, the "TC: unit is read only" will now say "TC0: unit is read only" going forward without regard to whether you said TC or TC0.

Your third question:
> when I attach the tc0 without the -r flag, and nothing was actually written to it (it was only read), when I quit the simulator, the following appears:
> 
> sim> q
> Goodbye
> TC0: writing buffer to file
> Why would it write the file that was never changed?

Good question.  The code specifically keeps track of actual writes to the device and only writes the buffer on detach (which is what happens at quit time) IF a write had happened.  This functionality was added to avoid the potential to mangle alternate format DECtapes (18bit vs 12bit vs 16bit).  Maybe you actually attached a 16bit DECtape and then while the OS was running, you "MOUNT"ed it and the MOUNT for the file system writes a dirty/mounted bit somewhere in the header which normally would get cleared by an OS dismount so the OS can detect a clean file system.  Both the dirty bit write and its clearing would be writes to the device which most appropriately should cause the buffer to be written back to the file even if you hadn't actually written any files to the device.  That's my theory anyway.  I've revised the TC device code to more sanely report activities.  Please confirm that things look OK now.

**Comment by al20878** [comment] 2021-04-16 23:17
> As it turns out, for this device, there is no formal software command to write lock the tape device

This only applies when software can override the "physical" setting (which it can't when there was the ``-r`` flag used, which represents the tape "ring" or a write-lock button on the disk drive front panel).  The ``TC`` logic is now fixed to the point that when I attach it "read-only" it automatically shows as "write locked" now.  It also seems to correctly refuse making it write-enabled in this case (I guess it's by design) but with a bit of an obscure error reported:
```
sim> set tc0 writeenabled
TC0: Already attached
```
Well, as for the disk attachment, there's still the same mixup:
```
sim> att -r rk dos_rk.dsk
RK0: unit is read only
sim> sh rk
RK      address=17777400-17777417, vector=220, BR5, 8 units
  RK0   1247KW, attached to dos_rk.dsk, read only, write enabled
        RK05, SIMH format
```
and for other tape device as well:
```
sim> att -re tm 11sp18.tap
TM0: unit is read only
TM0: Tape Image '11sp18.tap' scanned as SIMH format
sim> sh tm
TM      address=17772520-17772533, vector=224, BR5, 8 units
  TM0   attached to 11sp18.tap, read only, write enabled, SIMH format
        unlimited capacity
```

> simh device names allow for TC and TC0  to be equivalent

Yes, but when you do ``sh tc`` the difference becomes very obvious, ``TC`` standing for the entire controller, while ``TCn`` denoting individual units.

> I've changed that API to emit the appropriate unit name on these messages.

Thanks.  Confirmed.

>  Please confirm that things look OK now.

Yes, there's no spurious ``writing buffer to file`` message anymore.  And the tape wasn't mounted or anything like that.  It was only read (merely, for obtaining its catalog), so the ``write`` part was quite baffling.  Thanks for fixing that, too!

**Comment by al20878** [comment] 2021-04-16 23:21
> ``TC0: writing buffer to file``

May I have a suggestion that the file name is also printed in this message, when it is emitted?

``writing buffer to dos005.dta``

or something like that

**Comment by al20878** [comment] 2021-04-17 04:03
Found another minor inconsistency:
```
sim> help rha
...
Each RH adapter implements these registers:

The RHA device implements these registers:
```
the first heading seems to be extra (change ``rha`` to ``rhb``: the second heading changes, but the first one remains).
I guess it's a disconcert because of the static help text and the ``fprint_reg_help[_ex]()`` routine that adds the second device-specific heading.  Seems like easy to fix, though :-)

**Comment by al20878** [comment] 2021-04-17 04:13
And yet another weird thing:
```
$ ./pdp11

PDP-11 simulator V4.0-0 Current        git commit id: 28adebc1
sim> set 11/40
sim> sh dev
...
RHB     disabled
...
RS      disabled
...
sim> set rs ena
Device RHB interrupt vector conflict with TM at 0224
sim> sh dev
...
RHB     address=17772440, vector=224, BR5
...
RS      Massbus adapter -1 (RH@), 8 units
```
The last line looks like it went out of order...  In the default config,``rp`` is enabled and is using ``rha``, and if I disable ``rp`` first, then ``rs`` gets placed onto `rha``, and no ``-1`` occurs.

**Comment by markpizz** [comment] 2021-04-17 19:57
> And yet another weird thing:
> 
> > $ ./pdp11
> > 
> > PDP-11 simulator V4.0-0 Current        git commit id: 28adebc1
> > sim> set 11/40
> > sim> sh dev
> > ...
> > RHB     disabled
> > ...
> > RS      disabled
> > ...
> > sim> set rs ena
> > Device RHB interrupt vector conflict with TM at 0224
> > sim> sh dev
> > ...
> > RHB     address=17772440, vector=224, BR5
> > ...
> > RS      Massbus adapter -1 (RH@), 8 units
> The last line looks like it went out of order... In the default config,rp is enabled and is using rha, and if I disable rp first, then rs gets placed onto rha, and no -1 occurs.

In this case, you've already been told of the real failure (the RHB and TM conflict), so we're not really worried about any remaining tangled mess or incomplete auto configure.  Both the RHB and TM devices have hard set vectors which are the same value, and thus both configured concurrently doesn't work.  You could manually set every device address and vector (not auto configuring) specifically avoiding conflicts, but then you'd also have to manually configure every device in your OS to reflect exactly how you setup the hardware.

**Comment by al20878** [comment] 2021-04-17 21:42
> so we're not really worried about any remaining tangled mess or incomplete auto configure

If ``rp`` gets disabled belatedly. ``rha`` remains, yet ``rs`` gets assigned to ``rhc``... It looks like the only way out of this mess is to quit the simulator and restart...  It should not have allowed ``rs`` to be enabled and go into the conflict, in the first place.  Another example of the conflict that not even announced as such until one tries to boot, is this:
```
$ ./pdp11

PDP-11 simulator V4.0-0 Current        git commit id: 28adebc1
sim> set 11/20
sim> set rc ena
sim> sh dev
...
RC      address=17777440-17777457, vector=210, BR5
...
HK      address=17777440-17777477, vector=210, BR5, 8 units
...
```

**Comment by markpizz** [comment] 2021-04-18 00:15
The ability for the simulator to perform the necessary consistency check is not in the code path invoked by the general purpose ```SET <device> ENABLE/DISABLE``` command.  You may be messing with any number of things with commands like this and changing other stuff before actually needing the configuration to work.  The required sanity checking is performed before a ```BOOT <device-unit>``` and can be explicitly invoked by a ```SHOW IOSPACE``` command.

**Comment by markpizz** [comment] 2021-04-18 00:18
The fact that you got the earlier warning when you enabled the RS device is due to it NOT being a Unibus/Qbus device but a mass bus device and thus the internal device logic engages the massbus allocation paths that have the side effect of performing the I/O bus sanity check.

**Comment by al20878** [comment] 2021-04-18 16:43
Ok, ``SHOW IOSPACE`` is a nice hint.  Thanks!

Can you please comment on my earlier posts, that followed your previous replies?

I have a few more notes about the simulated _drives_ but I guess I cannot post them yet because I don't want them to fall thru the cracks :-)

**Comment by markpizz** [comment] 2021-04-18 18:48
The various inconsistent disk/tape messages about read-only and write enabled should be fixed.  The real solution to this is to have global code which solves this consistently.  The problem is that each device (at least several in almost all simulators) each have code local to that device which is repeated mostly the same way (sometimes different depending on whether the device supports software write lock).  More than 50 source code files are affected.  Note this is across all the simh simulators not just the PDP11.

-----------------

I'll remove the redundant RH help register message.

-----------------

I'll add the filename to the various buffer flushing messages.  There are a good number of DEVICES in several simulators (~6+) which have this issue.

**Comment by al20878** [comment] 2021-04-18 23:15
Thanks.

How about the TC message about ``writeenable``?  Should it be changed to 
```
sim> set tc0 writeenabled
TC0: Already attached __read-only__
```
I was basically playing with very "old" PDP11 hardware lately, and so was also noting that the ``RC`` and ``RF`` drives attached without writing to them, still emit the ``writing buffer`` message (just like ``TC`` used to do).  Sometimes, the file would remain 0-sized (because there was nothing written by the OS, and that was a "new" drive), yet the message would still be shown.

Side note: please the spelling of ``asynchronous`` (no ending ``e``) in ``scp.c``:
```
      "+sh{ow} a{synch}             show asynchronouse I/O state\n" 
```

**Comment by markpizz** [comment] 2021-04-18 23:29
> How about the TC message about writeenable? Should it be changed to
>
> > sim> set tc0 writeenabled
> > TC0: Already attached __read-only__

These messages will be consistent across all devices when I get done with the changes.

> I was basically playing with very "old" PDP11 hardware lately, and so was also noting that the RC and RF drives attached without writing to them, still emit the writing buffer message (just like TC used to do). Sometimes, the file would remain 0-sized (because there was nothing written by the OS, and that was a "new" drive), yet the message would still be shown.

Devices which buffered their data in RAM historically have always loaded the data at attach time and written it back at detach time.  The DECtape cases required special handling to keep track of actual writing to the buffered content.  This was due to the fact that there are 3 separate formats of DECtape images, some which have unused bits mixed in with the data, while others don't.  If someone attached with the wrong format, the attach logic could ignore some real data that meant something in the correct format and thus the write back could result in corrupted files.  Specific effort was made to visit each of these DECtape cases and add logic to the device to keep track if data was actually written and only then actually flush the buffered content at detach time.  This avoids the corruption potential.  If someone attaches a wrong format drive and then writes to it anyway, then they've actively corrupted the container's contents which is their fault and not simh's.  So, back to devices which buffer data and don't have multiple formats.  These cases are a don't matter since there is no room for corruption and the extra work to track down and then enhance the logic within each simulated device at best removes the detach message, and at worst introduces bugs.  Not worth the effort.

> Side note: please the spelling of asynchronous (no ending e) in scp.c:
> 
> >      "+sh{ow} a{synch}             show asynchronouse I/O state\n" 

Will be fixed.  Thanks.

**Comment by al20878** [comment] 2021-04-19 14:46
> These messages will be consistent across all devices when I get done with the changes.

Awesome.

>  Not worth the effort.

Okay, understood.

**Comment by al20878** [comment] 2021-04-20 03:11
I have checked your changes, they look good.  One wrinkle I noticed now is this:
```
sim> help tc show

TC device SHOW commands:

show TC ADDRESS                 Bus address
show TC VECTOR                  Interrupt vector
show TC DEBUG                   Displays debugging status for device TC
show TCn write enabled          Write enable drive
sim> show tc write enabled
Non-existent parameter: WRITE
sim> show tc writeenabled
Non-existent parameter: WRITEENABLED
sim> show tc0 write enabled
write locked
Non-existent parameter: ENABLED
sim> show tc0 writeenabled
Non-existent parameter: WRITEENABLED
```
Something's off -- all combinations gave me an error back, even when I used it exactly as it was shown in ``help``, with a space between ``write`` and ``enabled``.

**Comment by al20878** [comment] 2021-04-20 03:36
BTW,

```
static t_stat td_svc (UNIT *uptr)
{
...
        uint16 c, w;
...
    case TD_READ1:
...
        c = 0;
        for (i = 0; i < (data_size + 2); i++) {         /* Calculate checksum */
            w = (ctlr->obuf[i] << ((i & 0x1) ? 8 : 0));
            c = c + w + ( (uint32)((uint32)c + (uint32)w) > 0xFFFF ? 1 : 0);
            }
```
can be re-written without any checks:  the packet cannot be longer than 128, plus minus a few bytes, meaning that if you take ``c`` as a 32-bit integer, it would never overflow when 16-bit words summed to it.  So at the end, you can just fold all the 16-bit carries (accumulated in the high-order word) back into the result at once (this also eliminates ``w`` as unnecessary):
```
    uint32 c;
    ...
        for (i = 0; i < (data_size + 2); i++) {         /* Calculate checksum */
            c += (uint16) ctlr->obuf[i] << ((i & 1) ? 8 : 0);
        }
        c += c >> 16;
 ```
then the assignments of the result (that follow the loop) no need to change (as they already do the proper mask/shift):
```
        ctlr->obuf[ctlr->obptr++] = (c & 0xFF);         /* Checksum L */
        ctlr->obuf[ctlr->obptr++] = ((c >> 8) & 0xFF);  /* Checksum H */
```
Same at ``case TD_END:``...

**Comment by markpizz** [comment] 2021-04-20 19:11
> BTW in PDP11/pdp11_td.c,

Those facts may be true, but given that no one in the world would ever notice the efficiency improvements here and this is a case of "if it ain't broke, don't fix it", so no changes are necessary.

**Comment by al20878** [comment] 2021-04-20 21:47
> given that no one in the world would ever notice the efficiency improvements

This wasn't exactly about efficiency improvements, that's actually how one would calculate a one's complement checksum (which is exactly what's expected to be done there).

**Comment by markpizz** [comment] 2021-04-21 18:57
> > given that no one in the world would ever notice the efficiency improvements
>
> This wasn't exactly about efficiency improvements, that's actually how one would calculate a one's complement checksum 
(which is exactly what's expected to be done there).

I'm not questioning your analysis.  The second reason is the most relevant "if it ain't broke, don't fix it" applies.   This is another way of saying that just because you might not have written some piece of simh code this way, doesn't mean it should be changed.  Sorry.

**Closed** 2021-06-03 18:49 UTC
