### ISSUE TITLE
AltairZ80: ^E doesn't work when attaching SIO to Telnet (port 23)

### ISSUE THREAD

**Issue by Ster0pes** [simh/simh#1172] opened 2023-04-19 19:28 UTC
- #### Context
I'm trying to use the AltairZ80 simulator via a Telnet session. Reason for that is that I would like to control the simulator through the SIMH console, and see the Altair's output in a separate window.
I attach the SIO device to port 23 like this:
`attach SIO 23`
Then I execute a script that does the following:
```
set cpu 8080,noitrap,octal
set sio upper,ansi
d sr 0
load basic\8kbasic40.bin 0
g 0
```

Then I start a Telnet session using TeraTerm. It says it is connected to SIO, line 0. If I start another Telnet session, it connects to SIO line 1.
So far so good you would say, but here's the problem: I can no longer use ^E in the SIMH console to interrupt the simulator.

When I enable Telnet like this:
`set CONSOLE TELNET=23`
^E keeps working. However, using this method I can only connect one Telnet session. It gets connected to CON-TELNET.

Is it possible to get ^E working using the first method?

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
Altair 8800 (Z80) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        FrontPanel API Version 12
    Host Platform:
        Compiler: Microsoft Visual C++ 15.00.30729.01
        Simulator Compiled as C arch: x86 (Release Build) on Apr  1 2022 at 12:44:27
        Build Tool: simh-Visual-Studio-Project
        Memory Access: Little Endian
        Memory Pointer Size: 32 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Microsoft Windows [Version 10.0.19045.2846]
        Architecture: x86 on AMD64, Processors: 4
        Processor Id: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel, Level: 6, Revision: 3c03
        Processor Name: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
        tar tool: bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp
        curl tool: curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
        git commit id: b8015349
        git commit time: 2022-04-01T12:37:11-07:00
```

- #### how you built the simulator or that you're using prebuilt binaries
I downloaded the prebuilt binaries from Github.

- #### the simulator configuration file (or commands) which were used when the problem occurred.
I'm not using a config file.

- #### the expected behavior and the actual behavior
Expected behavior: while the simulator is running I can interrupt it using ^E.
Actual behavior: when I directly attach SIO to Telnet ^E doesn't work and I can't interrupt the simulator.

**Comment by markpizz** [comment] 2023-04-19 19:44
The only missing piece for me to reproduce this would be the 8kbasic40.bin file.  Where can I find that?

**Comment by Ster0pes** [comment] 2023-04-21 17:50
I built AltairZ80.exe using the latest code. Got this error:
`LINK : fatal error LNK1104: cannot open file '..\BIN\NT\Win32-Release\BuildTools\BuildROMs.exe'`
No wonder, the BuildTools folder is completely empty :)
Don't know if that's alarming but I got an AltairZ80.exe anyhow.

I tried both methods I mentioned, so `attach SIO 23` and `set CONSOLE TELNET=23`.
With the new executable I'm able to interrupt the simulator in both situations using ^E.
Thank you so much for your lightning-fast replies and fix!

There one last (somewhat unrelated) question I'd like to ask, out of curiosity.
When I attach the simulator to a Telnet port and start a Telnet session in TeraTerm, at first nothing happens.
Only after I load and run BASIC (for example) the text "Connected to the Altair 8800 (Z80) simulator" appears in the TeraTerm window.
Why is that? Is the Telnet connection actually established only when there is some form of activity from the Altair simulator?

**Comment by markpizz** [comment] 2023-04-21 20:02
The logic in the simulator code (which is actually implemented by generic capabilities of the simh framework and not something specific in simulator code), runs using various capabilities of the simh framework which are only in operation when simulators are executing instructions.  This part of the system doesn't notice the arrival of your telnet connection until it receives the telnet connection while the simulator is executing instructions.  That part of the system then emits the connection message and your connection is then available for use by the simulator.

Please close this issue since the problem you reported is fixed.

**Closed** 2023-04-21 21:04 UTC

**Comment by markpizz** [comment] 2023-04-21 22:14
I missed this:

> I built AltairZ80.exe using the latest code. Got this error:
> LINK : fatal error LNK1104: cannot open file '..\BIN\NT\Win32-Release\BuildTools\BuildROMs.exe'
> No wonder, the BuildTools folder is completely empty :)
> Don't know if that's alarming but I got an AltairZ80.exe anyhow.

Well, since you initially used a pre-built binary, I presumed you would do the same again.  However, now that you actually tried to build on your own, what compiler version did you use? 
Also, it would be useful for you to:

   > rmdir/s <where-you-ve-got-simh-locally>\BIN

And, then please rebuild the AltairZ80 simulator, and capture the contents of the IDE Output window and paste that in your response to this message.  You should prefix the pasted content with triple back-ticks and put triple back-ticks after as well.  The back tick character is: \`

**Comment by Ster0pes** [comment] 2023-04-22 10:21
> Well, since you initially used a pre-built binary, I presumed you would do the same again.
I could have done that indeed. However I wrongly assumed that the releases page was the only place to look for pre-built binaries.

> However, now that you actually tried to build on your own, what compiler version did you use?
I donloaded Visual Studio Community 2022, let it convert al projects and then built the AltairZ80 project. I'm not at my own PC right now, so I can't quicky look up compiler version etc.

> Also, it would be useful for you to:
>> rmdir/s <where-you-ve-got-simh-locally>\BIN
The BIN folder was created and populated. Only the BuildTools folder seemed to be empty.

> And, then please rebuild the AltairZ80 simulator, and capture the contents 
I'll do that as soon as I get home.

**Comment by Ster0pes** [comment] 2023-04-23 19:54
Strange. I just tried rebuilding the AltairZ80 project and now it works...

**Comment by markpizz** [comment] 2023-04-23 20:06
In Visual Studio, Right-Click on the simh solution at the top of the solution explorer and select "Clean Solution".  Then try to build the AltairZ80 project.  If this works, then we're done.  If not, then please send what appears in the Output window.
